// One-time historical source research: bounded anonymous IBU reads, no database writes.
import {mkdirSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';
const api='https://biathlonresults.com/modules/sportapi/api/';const out='artifacts/season-research';mkdirSync(out+'/raw',{recursive:true});
const receipt=[];const athletes=new Set(['BTFRA12906200101','BTNOR12002199701','BTNOR11806199901','BTSWE12803199701','BTFRA11107199501','BTITA10504200001']);
async function get(method,params,key){if(!['Events','Competitions','CupResults','Results','AnalyticResults'].includes(method))throw new Error('METHOD');const url=api+method+'?'+new URLSearchParams(params);const r=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(20000),headers:{'user-agent':'WinterSportsHub/2.0 historical-editorial-research'}});if(!r.ok)throw new Error('SOURCE_HTTP_'+r.status);if(!r.body)throw new Error('NO_BODY');const reader=r.body.getReader();let size=0;const parts=[];try{while(true){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>3*1024*1024){await reader.cancel();throw new Error('SIZE_LIMIT')}parts.push(value)}}finally{reader.releaseLock()}const raw=Buffer.concat(parts);const data=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw));writeFileSync(out+'/raw/'+key+'.json',raw);receipt.push({key,url,fetchedAt:new Date().toISOString(),sha256:createHash('sha256').update(raw).digest('hex'),bytes:raw.length});await new Promise(r=>setTimeout(r,180));return data;}
const report={season:'2526',events:[],races:[],errors:[],databaseWrites:0};
try{
 report.standings=await get('CupResults',{CupId:'BT2526SWRLCP__SMTS'},'standings');
 const events=await get('Events',{SeasonId:'2526',Level:'1'},'events');if(!Array.isArray(events)||events.length>20)throw new Error('EVENTS_CONTRACT');
 for(const e of events){if(!/^BT2526[A-Z0-9_]+$/.test(e.EventId))throw new Error('EVENT_ID');const comps=await get('Competitions',{EventId:e.EventId},'competitions-'+e.EventId);if(!Array.isArray(comps)||comps.length>50)throw new Error('COMPETITIONS_CONTRACT');report.events.push({event:e,competitions:comps});
  for(const c of comps){if(!/^BT2526[A-Z0-9_]+SM(?:IN|SI|SP|PU|MS)$/.test(c.RaceId))continue;try{const results=await get('Results',{RaceId:c.RaceId},'results-'+c.RaceId);const selected=(results.Results||[]).filter(r=>athletes.has(r.IBUId));report.races.push({event:e,competition:c,meta:Object.fromEntries(Object.entries(results).filter(([k])=>k!=='Results')),athletes:selected,rowsCount:results.Results?.length||0});}catch(error){report.errors.push({raceId:c.RaceId,error:error.message})}}
 }
 // Probe final race components only; no aliases are assumed equivalent before labels are reviewed.
 const last=report.races.filter(r=>r.competition.RaceId.includes('SWRLCP')).sort((a,b)=>a.competition.StartTime.localeCompare(b.competition.StartTime)).at(-1);
 if(last){report.analyticProbe=[];for(const type of ['CRST','RNGT','STTM']){try{const d=await get('AnalyticResults',{RaceId:last.competition.RaceId,TypeId:type},'analysis-'+last.competition.RaceId+'-'+type);report.analyticProbe.push({type,meta:Object.fromEntries(Object.entries(d).filter(([k])=>k!=='Results')),athletes:(d.Results||[]).filter(r=>athletes.has(r.IBUId)),count:d.Results?.length||0})}catch(error){report.errors.push({analytic:type,error:error.message})}}}
}catch(error){report.errors.push({fatal:error.message})}
writeFileSync(out+'/report.json',JSON.stringify(report,null,2));writeFileSync(out+'/receipts.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify({events:report.events.length,races:report.races.length,errors:report.errors,databaseWrites:0},null,2));if(report.errors.some(e=>e.fatal||e.raceId))process.exitCode=1;
