// Read-only editorial evidence receipt. Never copies source articles or publishes sport data.
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {load} from 'cheerio';
const sources=JSON.parse(readFileSync(new URL('../../content/editorial/sources.json',import.meta.url),'utf8'));const receipts=[];mkdirSync('artifacts/editorial',{recursive:true});
for(const source of sources){try{
 const u=new URL(source.url);if(u.protocol!=='https:'||!['www.biathlonworld.com','kontiolahtibiathlon.com'].includes(u.hostname)||u.username||u.password)throw new Error('SOURCE_NOT_ALLOWED');
 const r=await fetch(source.url,{redirect:'manual',signal:AbortSignal.timeout(20000),headers:{'user-agent':'WinterSportsHub/1.8 editorial-verification'}});if(!r.ok){await r.body?.cancel();throw new Error('HTTP_'+r.status)}
 if(!r.headers.get('content-type')?.includes('text/html'))throw new Error('NOT_HTML');const reader=r.body.getReader();const parts=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>4*1024*1024){await reader.cancel();throw new Error('BODY_LIMIT')}parts.push(value)}}finally{reader.releaseLock()}
 const bytes=Buffer.concat(parts),$=load(bytes.toString('utf8'));$('script,style,nav,footer,noscript').remove();const text=$('body').text().replace(/\s+/g,' ').trim();
 receipts.push({id:source.id,url:source.url,httpStatus:200,fetchedAt:new Date().toISOString(),sha256:createHash('sha256').update(bytes).digest('hex'),bytes:size,title:$('h1,h2').first().text().trim().slice(0,180),season202526Present:/2025[\/–-](?:20)?26/.test(text),season202627Present:/2026[\/–-](?:20)?27/.test(text),evidenceTerms:{perrot1263:/1263/.test(text),laegreid984:/984/.test(text),giacomel797:/797/.test(text),fiveConsecutive:/fifth consecutive individual|five consecutive individual|fifth straight win/i.test(text),laegreid183of190:/183 of 190/.test(text)},transportOnly:true});
 }catch(e){receipts.push({id:source.id,url:source.url,error:e.message,cause:e.cause?.code||null})}}
// Anonymous datacenter standings probe. Failure does not authorize guessed points or race IDs.
let standings;try{const url='https://biathlonresults.com/modules/sportapi/api/CupResults?CupId=BT2526SWRLCP__SMTS';const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('HTTP_'+r.status);const text=await r.text();if(text.length>1000000)throw new Error('API_BODY_LIMIT');const raw=JSON.parse(text);standings={url,sha256:createHash('sha256').update(text).digest('hex'),fetchedAt:new Date().toISOString(),data:raw};writeFileSync('artifacts/editorial/standings.json',JSON.stringify(standings,null,2));}catch(e){standings={error:e.message}}
const report={checkedAt:new Date().toISOString(),receipts,standingsAvailable:!!standings.data,standingsError:standings.error,databaseWrites:0,scope:'Transport and content presence, not automatic semantic fact verification'};writeFileSync('artifacts/editorial/source-receipts.json',JSON.stringify(report,null,2));console.log(JSON.stringify({sources:receipts.length,received:receipts.filter(r=>r.httpStatus===200).length,errors:receipts.filter(r=>r.error),standingsAvailable:report.standingsAvailable,standingsError:report.standingsError},null,2));
