import Link from 'next/link';import {ArrowUpRight,CalendarDays,MapPin,Target,Mountain} from 'lucide-react';import type {StageModel} from '../../lib/stage-catalog.mjs';import {stageCountry,stageDateRange,stagePlace,stageSeries,stageStatus} from '../../lib/stage-catalog.mjs';import {genderLabel,safeHttpsUrl,sportLabel} from '../../lib/domain.mjs';import {raceLabel} from '../../lib/viewer.mjs';import candidates from '../../content/stage-photo-candidates.json';import {StagePhoto} from './StagePhoto';import styles from './Stages.module.css';
export function StageCard({model}:{model:StageModel}){
 const {competition:c,summary,races}=model;const source=safeHttpsUrl(c.source_url),photo=candidates.find(p=>p.competitionKey===c.external_key);const Icon=c.sport==='biathlon'?Target:Mountain;const preview=races.filter(r=>r.status!=='cancelled').slice(0,3);
 return <article className={`${styles.card} ${c.sport==='biathlon'?styles.biathlon:styles.ski}`} data-stage-id={c.id} data-sport={c.sport} data-scope={c.scope} data-status={c.status}>
  <div className={styles.artwork}><StagePhoto competitionKey={c.external_key} sport={c.sport}/><div className={styles.cardBadges}><span><Icon size={14} aria-hidden="true"/>{sportLabel(c.sport)}</span><span className={c.status==='cancelled'?styles.cancelled:['provisional','tentative'].includes(c.status)?styles.provisional:styles.neutral}>{stageStatus(c.status)}</span></div></div>
  <div className={styles.cardBody}><p className={styles.series}>{stageSeries(c.series)}</p><h2><Link href={`/competitions/${c.id}`}>{stagePlace(c).split(',')[0]}</Link></h2><p className={styles.location}><MapPin size={13} aria-hidden="true"/>{stageCountry(c)} · {c.scope==='russia'?'Россия':'Международные'}</p><p className={styles.stageName}>{c.name!==c.location?c.name:'Сезон 2026/27'}</p><p className={styles.dates}><CalendarDays size={16} aria-hidden="true"/>{stageDateRange(c.start_date,c.end_date)}</p>
   <div className={styles.programmeMeta}>{summary?<><span><strong>{summary.total||'—'}</strong> {summary.total?'записей гонок':'программа ожидается'}</span><span>{summary.cancelled?`${summary.cancelled} отменено`:summary.timed?`${summary.timed} со временем`:'Время уточняется'}</span></>:<span>Программа временно недоступна</span>}</div>
   {preview.length>0?<ol className={styles.preview}>{preview.map(r=><li key={r.id}><time dateTime={r.event_date||undefined}>{r.event_date?.slice(8,10)}.{r.event_date?.slice(5,7)}</time><span>{raceLabel(r)}<small>{genderLabel(r.gender)}</small></span></li>)}</ol>:<p className={styles.emptyProgramme}>{summary?.cancelled?'В базе есть отменённые записи. Их история сохранена в программе.':summary?'Даты этапа опубликованы. Подробные старты появятся после проверки программы.':'Не удалось загрузить программу. Это не отмена этапа.'}</p>}
   {summary&&summary.total>0&&<p className={styles.countNote}>Квалификации и финалы считаются отдельно.</p>}
   <div className={styles.cardBottom}><Link className={styles.open} href={`/competitions/${c.id}`}>Программа этапа <ArrowUpRight size={18} aria-hidden="true"/></Link>{source&&<a className={styles.source} href={source} target="_blank" rel="noopener noreferrer" aria-label={`Первоисточник: ${c.name}, ${stagePlace(c)}`}>Источник ↗</a>}</div>
   {photo&&<a className={styles.archiveLink} href={photo.sourcePage} target="_blank" rel="noopener noreferrer">Фото из {photo.place} · архив 2025/26 ↗</a>}
  </div>
 </article>;
}
