'use client';
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';import {ArrowDown,ArrowUpRight,ChevronLeft,ChevronRight} from 'lucide-react';import {athleteVisuals,visualCopy} from '../../lib/athlete-visuals';import {AthletePhoto} from './AthletePhoto';import styles from './FullScreen.module.css';
export function FullscreenHero(){
 const [active,setActive]=useState(0),[motion,setMotion]=useState('initial'),root=useRef<HTMLElement>(null),photo=athleteVisuals[active];
 useEffect(()=>{
  let cancelled=false,revert:undefined|(()=>void);const el=root.current;if(!el)return;
  const media=window.matchMedia('(prefers-reduced-motion: reduce)');if(media.matches){setMotion('reduced');return}
  void import('gsap').then(({gsap})=>{if(cancelled)return;const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{
   // Animate the editorial layer only. Never zoom/stretch/warp the original photograph.
   gsap.fromTo('[data-star-copy]',{y:18,opacity:.7},{y:0,opacity:1,duration:.65,ease:'power3.out',clearProps:'transform,opacity'});
  },el);return()=>ctx.revert()});revert=()=>mm.revert();setMotion('ready')}).catch(()=>{if(!cancelled)setMotion('unavailable')});
  return()=>{cancelled=true;revert?.()};
 },[active]);
 const change=(n:number)=>setActive((n+athleteVisuals.length)%athleteVisuals.length);
 return <section ref={root} className={styles.hero} data-fullscreen-hero data-motion={motion} data-active-athlete={photo.key} aria-label="Лица зимнего спорта"><AthletePhoto key={photo.key} photo={photo} eager/><div className={styles.shade} aria-hidden="true"/><div className={styles.heroLead}><span className={styles.kicker}>WINTER SPORTS HUB / 2026–27</span><h1>Весь сезон.<br/><span>В вашем ритме.</span></h1><p>Биатлон и лыжные гонки.<br/>Люди. Гонки. Настоящие истории.</p></div><div className={styles.identity} data-star-copy><span className={styles.sport}>{photo.sport} / Фотохроника</span><p className={styles.given}>{photo.given}</p><h2 className={styles.family}>{photo.family}</h2><p className={styles.tagline}>{visualCopy[photo.key]}</p><div className={styles.heroActions}><Link href="/competitions" className={styles.primary}>Открыть этапы <ArrowUpRight size={18} aria-hidden="true"/></Link><Link href={photo.href} prefetch={false}>{photo.cta}</Link></div></div><div className={styles.frameNumber} aria-hidden="true">{String(active+1).padStart(2,'0')}<span> / 05</span></div><div className={styles.credit}><span>{photo.scene}</span><Link href={'/photo-credits#'+photo.key} prefetch={false}>Фото: {photo.author} · {photo.license} ↗</Link><a href={photo.originalUrl} target="_blank" rel="noopener noreferrer">Открыть исходный кадр ↗</a>{!photo.highResolution&&<span>Архивный портрет 285×390. Без искусственного увеличения.</span>}</div><div className={styles.bottomBar}><div className={styles.selector} role="group" aria-label="Выбрать спортсмена на обложке">{athleteVisuals.map((p,i)=><button type="button" key={p.key} aria-pressed={i===active} onClick={()=>change(i)} aria-label={`Показать: ${p.name}`}><span>{String(i+1).padStart(2,'0')}</span>{p.family}</button>)}</div><div className={styles.arrows}><button type="button" aria-label="Предыдущая фотография" onClick={()=>change(active-1)}><ChevronLeft size={20}/></button><button type="button" aria-label="Следующая фотография" onClick={()=>change(active+1)}><ChevronRight size={20}/></button><a href="#season-content" aria-label="Перейти к календарю сезона"><ArrowDown size={20}/></a></div></div><span className={styles.srOnly} role="status" aria-live="polite">{photo.name}. {photo.scene}.</span><noscript><p className={styles.noScript}>Другие реальные фотографии доступны в разделе <a href="/athletes">«Лица зимы»</a>. Автоматическая смена кадров не используется.</p></noscript></section>;
}
