'use client';
import Link from 'next/link';import {useMemo,useState,useTransition} from 'react';import {useRouter} from 'next/navigation';
import {useSelection} from './SelectionProvider';import {SaveButton} from './SaveButton';import {ExportSelection} from './ExportSelection';
import {projectSelection} from '../../lib/selection.mjs';import {countLabel} from '../../lib/count-label.mjs';import type {StageModel} from '../../lib/stage-catalog.mjs';
import {stagePlace,stageStatus,stageDateRange} from '../../lib/stage-catalog.mjs';import {raceLabel} from '../../lib/viewer.mjs';import {formatDate,genderLabel,raceStatus,safeHttpsUrl} from '../../lib/domain.mjs';import styles from './Personal.module.css';
export function MySeason({models,unavailable,programmeUnavailable,today}:{models:StageModel[];unavailable:boolean;programmeUnavailable:boolean;today:string}){
 const {selection,mode,message,clear}=useSelection();const [confirm,setConfirm]=useState(false),[view,setView]=useState('all');const [pending,startTransition]=useTransition();const router=useRouter();
 const resolved=useMemo(()=>projectSelection(selection,models),[selection,models]);
 const rows=resolved.races.filter(r=>view==='all'||view==='cancelled'&&r.status==='cancelled'||view==='upcoming'&&r.status!=='cancelled'&&r.status!=='completed'&&!!r.event_date&&r.event_date>=today);
 const hasSelection=selection.stages.length+selection.races.length>0;
 const refresh=()=>startTransition(()=>router.refresh());
 return <>
  <header className="calendarHeader"><h1 className={styles.title}>Мой сезон.</h1><p className={styles.intro}><strong>Только то, что важно вам.</strong> Сохраните этап целиком или отдельную гонку. Подборка собирается из опубликованной базы при загрузке страницы и нажатии «Обновить данные»; факты о гонках не сохраняются в избранном.</p></header>
  <noscript><p>Для локального избранного нужен JavaScript. Общий календарь и программы этапов доступны без создания аккаунта.</p></noscript>
  <div className={styles.toolbar}><div><p>Сохранено: <strong>{countLabel(selection.stages.length,'этап','этапа','этапов')}</strong> · <strong>{countLabel(selection.races.length,'отдельная гонка','отдельные гонки','отдельных гонок')}</strong></p><p>{mode==='loading'?'Читаем выборку браузера…':mode==='memory'?'Сохранение запрещено браузером: выборка действует до перезагрузки.':'Без регистрации. Избранное хранится только в этом браузере.'}</p></div><div className={styles.tools}><button type="button" onClick={refresh} disabled={pending}>{pending?'Обновляем…':'Обновить данные'}</button>{hasSelection&&<button type="button" className={styles.clear} onClick={()=>setConfirm(true)}>Очистить выборку</button>}</div></div>
  {confirm&&<div className={styles.notice}><p>Удалить сохранённые этапы и гонки из этого браузера? Общий календарь не изменится.</p><div className={styles.actions}><button type="button" onClick={()=>{clear();setConfirm(false)}}>Да, очистить выборку</button><button type="button" onClick={()=>setConfirm(false)}>Оставить</button></div></div>}
  {mode==='invalid'&&<p className={styles.notice}>Сохранённые данные имеют неподдерживаемый формат. Они не применены и не отправлены на сервер. Повреждённую запись можно удалить кнопкой внизу страницы или начать новую подборку.</p>}
  <p className={styles.message} role="status">{message}</p>
  {mode==='loading'?<p role="status">Загружаем локальный список…</p>:!hasSelection?<section className={styles.empty}><h2>Соберите свой зимний маршрут.</h2><p>Нажмите значок закладки на карточке этапа или гонки. Этап добавит в подборку все связанные опубликованные гонки — без создания дубликатов.</p><Link href="/competitions">Выбрать этапы →</Link><Link href="/calendar">Найти отдельную гонку →</Link></section>:unavailable?<div className={styles.notice} role="status">Не удалось загрузить опубликованные данные. Ваши закладки сохранены; это не означает отмену выбранных гонок. Повторите обновление.</div>:<>
   {resolved.stages.length>0&&<section><h2>Сохранённые этапы</h2><div className={styles.cards}>{resolved.stages.map(({competition:c,summary})=><article className={styles.stage} key={c.id} data-saved-stage={c.id}><small>{stageStatus(c.status)}</small><h3><Link href={`/competitions/${c.id}`}>{stagePlace(c)}</Link></h3><p>{stageDateRange(c.start_date,c.end_date)}</p><p>{summary?summary.total?`${countLabel(summary.total,'запись','записи','записей')} гонок в базе`:'Пока опубликованы только даты этапа':'Программа временно недоступна'}</p><SaveButton kind="stage" id={c.id} label={stagePlace(c)}/></article>)}</div></section>}
   {programmeUnavailable?<div className={styles.notice}>Программы сейчас недоступны. Список сохранённых этапов не удаляется; экспорт гонок временно выключен.</div>:<section><h2>Гонки моей подборки</h2><p className={styles.intro}>Гонки из сохранённого этапа появляются здесь при обновлении страницы. Личная закладка на той же гонке не создаёт второй записи.</p><div className={styles.filter} aria-label="Фильтр моей подборки">{[['all','Все даты'],['upcoming','Предстоящие'],['cancelled','Отменённые']].map(([value,title])=><button type="button" key={value} aria-pressed={view===value} onClick={()=>setView(value)}>{title}</button>)}</div><ExportSelection ids={rows.map(r=>r.id)}/>
    {rows.length===0?<p className={styles.empty}>По этому фильтру нет опубликованных гонок. Возможно, сохранён только этап без подробной программы.</p>:<div className={styles.rows}>{rows.map(r=><article className={styles.race} key={r.id} data-saved-race={r.id}><div className={styles.date}>{formatDate(r.event_date)}<br/>{r.start_time_msk?`${r.start_time_msk.slice(0,5)} МСК`:'Время уточняется'}</div><div><h3><Link href={`/race-center/${r.id}`}>{raceLabel(r)}</Link></h3><p>{r.location} · {genderLabel(r.gender)}</p><p className={r.status==='cancelled'?styles.cancelled:undefined}>{raceStatus(r.status)}</p>{r.competition_id&&selection.stages.includes(r.competition_id)&&<p>В составе сохранённого этапа. Удаление личной закладки не исключает гонку из программы этапа.</p>}{safeHttpsUrl(r.source_url)&&<a href={safeHttpsUrl(r.source_url)!} target="_blank" rel="noopener noreferrer">Первоисточник ↗</a>}</div><SaveButton kind="race" id={r.id} label={raceLabel(r)} compact/></article>)}</div>}
   </section>}
   {(resolved.missingStages.length>0||!programmeUnavailable&&resolved.missingRaces.length>0)&&<section className={styles.notice}><h2>Записи, которые сейчас не найдены</h2><p>Они могут быть вне сезона или временно не опубликованы. Это не подтверждённая отмена. Закладки не удалены автоматически.</p>{resolved.missingStages.map(id=><div className={styles.missing} key={'s'+id}><span>Этап №{id}</span><SaveButton kind="stage" id={id} label={`Этап №${id}`}/></div>)}{!programmeUnavailable&&resolved.missingRaces.map(id=><div className={styles.missing} key={'r'+id}><span>Гонка №{id}</span><SaveButton kind="race" id={id} label={`Гонка №${id}`}/></div>)}</section>}
  </>}
  <details className={styles.privacy}><summary>Хранение и ограничения подборки</summary><p>В localStorage записываются только версия формата, сезон и номера выбранных этапов и гонок. На новом устройстве, другом домене или после очистки браузера выборка не переносится. Одновременные действия в разных вкладках могут перезаписать друг друга — это не облачная синхронизация.</p><p>Избранное не даёт доступ к вашему личному календарю и не включает уведомления. При скачивании ICS номера выбранных гонок передаются серверу для получения текущих публичных записей; файл является разовой копией. Неизвестное время остаётся отметкой даты на весь день. Хостинг может обрабатывать технические сведения о запросах.</p><p>Для получения обновлений используйте подписку на календарный адрес проекта, а перед стартом — первоисточник. <Link href="/calendar/subscribe">О подписке →</Link></p></details>
 </>;
}
