import test from 'node:test';import assert from 'node:assert/strict';
import {loadAgentRegistry} from '../lib/agents/registry.mjs';
import {loadWorkers,workerForAgent} from '../lib/agents/workers.mjs';
import {buildEditorialPipeline} from '../lib/agents/pipelines.mjs';
import {MemoryAgentStore} from '../lib/agents/store-memory.mjs';

const registry=loadAgentRegistry();const workers=loadWorkers({registry});

test('every agent has exactly one worker declaration and existing deterministic entrypoints resolve',()=>{assert.equal(Object.keys(workers.workers).length,registry.agents.length);assert.equal(workerForAgent(workers,registry,'media-watch').enabled,true);assert.equal(workerForAgent(workers,registry,'photo-scout').mode,'github-action');assert.equal(workerForAgent(workers,registry,'publisher').enabled,false)});
test('model specialists are declared but disabled until model runtime is installed',()=>{for(const id of ['research','fact-check','editorial-writer','visual-director']){const w=workerForAgent(workers,registry,id);assert.equal(w.mode,'model-runtime');assert.equal(w.enabled,false)}});
test('memory store exposes only dependency- and gate-ready jobs',()=>{const graph=buildEditorialPipeline({registry,eventRef:'event:42'});const store=new MemoryAgentStore({registry});store.addMany(graph);assert.deepEqual(store.ready().map(j=>j.agentId),['research']);const research=graph[0],fact=graph[1];store.start(research.jobId);store.succeed(research.jobId,['evidence:1']);assert.deepEqual(store.ready().map(j=>j.agentId),['fact-check']);store.start(fact.jobId);store.succeed(fact.jobId,['approved-evidence:1']);assert.ok(store.ready().some(j=>j.agentId==='editorial-writer'))});
test('publisher remains blocked until approvals exist even after dependencies complete',()=>{const graph=buildEditorialPipeline({registry,eventRef:'event:99'});const store=new MemoryAgentStore({registry});store.addMany(graph);for(const j of graph.slice(0,-1)){const current=store.get(j.jobId);for(const dep of current.dependencies){const d=store.get(dep);if(d.status!=='succeeded'){if(d.status==='queued'){store.start(dep);store.succeed(dep)}}}if(store.get(j.jobId).status==='queued'){store.start(j.jobId);store.succeed(j.jobId)}}const pub=graph.at(-1);assert.ok(!store.ready().some(j=>j.jobId===pub.jobId));store.approve(pub.jobId,'fact-check-passed');store.approve(pub.jobId,'qa-passed');assert.ok(store.ready().some(j=>j.jobId===pub.jobId))});
test('invalid state transitions and retry exhaustion fail closed',()=>{const graph=buildEditorialPipeline({registry,eventRef:'event:7'});const store=new MemoryAgentStore({registry});store.addMany(graph);const research=graph[0];assert.throws(()=>store.succeed(research.jobId),/JOB_NOT_RUNNING/);for(let i=0;i<research.maxAttempts;i++){store.start(research.jobId);store.fail(research.jobId);if(i<research.maxAttempts-1)store.requeue(research.jobId)}assert.throws(()=>store.requeue(research.jobId),/JOB_ATTEMPTS_EXHAUSTED/)});
