import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {loadAgentRegistry} from '../lib/agents/registry.mjs';
import {loadArtifactRegistry,assertHandoff,validateArtifact} from '../lib/agents/handoff.mjs';
import {sourceAuthority} from '../lib/agents/artifacts.mjs';
import {loadSkillCatalog} from '../lib/agents/skills.mjs';

const registry=loadAgentRegistry();const artifacts=loadArtifactRegistry();
const evidence={packetId:'packet:1',topic:'Ruka schedule',createdAt:'2026-10-04T12:00:00Z',sources:[{sourceId:'fis',kind:'official',url:'https://www.fis-ski.com/example',publishedAt:null,observedAt:'2026-10-04T11:55:00Z'},{sourceId:'media',kind:'secondary',url:'https://example.com/report',publishedAt:'2026-10-04T10:00:00Z',observedAt:'2026-10-04T11:56:00Z'}],claims:[{claimId:'c1',text:'Official schedule states the event date.',kind:'fact',confidence:'verified',sourceIds:['fis'],mutable:true}],conflicts:[]};

test('official sources have higher deterministic authority than secondary/social context',()=>{assert.ok(sourceAuthority('official')>sourceAuthority('secondary'));assert.ok(sourceAuthority('secondary')>sourceAuthority('social'))});
test('Media Watch source snapshots hand off only to Research',()=>{const snapshot={snapshotId:'s1',kind:'official',sourceUrl:'https://www.fis-ski.com/calendar',fetchedAt:'2026-10-04T10:00:00Z',sha256:'a'.repeat(64),official:true};assert.equal(assertHandoff({fromAgent:'media-watch',toAgent:'research',type:'source-snapshot',value:snapshot,registry,artifactRegistry:artifacts}),true);assert.throws(()=>assertHandoff({fromAgent:'media-watch',toAgent:'fact-check',type:'source-snapshot',value:snapshot,registry,artifactRegistry:artifacts}),/HANDOFF_CONSUMER_FORBIDDEN/)});
test('research evidence handoff validates producer, consumer and packet structure',()=>{assert.equal(assertHandoff({fromAgent:'research',toAgent:'fact-check',type:'evidence-packet',value:evidence,registry,artifactRegistry:artifacts}),true);assert.throws(()=>assertHandoff({fromAgent:'research',toAgent:'editorial-writer',type:'evidence-packet',value:evidence,registry,artifactRegistry:artifacts}),/HANDOFF_CONSUMER_FORBIDDEN/)});
test('approved evidence cannot exist when fact check blocks',()=>{const approved={packet:evidence,report:{reportId:'fc:1',packetId:'packet:1',decision:'block',checks:[{claimId:'c1',decision:'unsupported',sourceRefs:['https://www.fis-ski.com/example'],note:'not enough'}]}};assert.throws(()=>validateArtifact('approved-evidence',approved,{artifactRegistry:artifacts}),/EVIDENCE_NOT_APPROVED/)});
test('fact-check pass cannot hide conflicted unsupported or stale claims',()=>{const report={reportId:'fc:2',packetId:'packet:1',decision:'pass',checks:[{claimId:'c1',decision:'conflicted',sourceRefs:['https://www.fis-ski.com/example'],note:'conflict'}]};assert.throws(()=>validateArtifact('fact-check-report',report,{artifactRegistry:artifacts}),/FACT_PASS_WITH_BLOCKING_CHECK/)});
test('curator cannot set deployable itself; verified media requires both external approvals',()=>{const curated={mediaId:'m1',athleteRef:'athlete:klaebo',confidence:'high',identityReviewed:true,rightsReviewed:true,deployable:true,sourceRefs:['https://commons.wikimedia.org/wiki/File:X.jpg']};assert.throws(()=>validateArtifact('curated-media-candidate',curated,{artifactRegistry:artifacts}),/CURATOR_CANNOT_SET_DEPLOYABLE/);const verified={mediaId:'m1',athleteRef:'athlete:klaebo',identityReviewed:true,rightsReviewed:true,approvals:['identity-reviewed','rights-reviewed'],sourceRefs:['https://commons.wikimedia.org/wiki/File:X.jpg'],credit:'Example / CC BY'};assert.equal(assertHandoff({fromAgent:'media-curator',toAgent:'visual-director',type:'verified-media',value:verified,registry,artifactRegistry:artifacts}),true);assert.throws(()=>validateArtifact('verified-media',{...verified,approvals:['identity-reviewed']},{artifactRegistry:artifacts}),/VERIFIED_MEDIA_GATE_MISSING:rights-reviewed/)});
test('named-person visual package rejects media lacking identity or rights approval',()=>{const visual={packageId:'visual:1',draftId:'draft:1',namedPersonMedia:true,media:[{mediaRef:'media:klaebo',identityReviewed:true,rightsReviewed:false,credit:'Photographer'}]};assert.throws(()=>validateArtifact('visual-package',visual,{artifactRegistry:artifacts}),/VISUAL_NAMED_PERSON_MEDIA_UNREVIEWED/)});
test('QA cannot claim pass while containing failed required check',()=>{const qa={reportId:'qa:1',passed:true,checks:[{name:'browser','status':'fail',note:'mobile overflow'}]};assert.throws(()=>validateArtifact('qa-report',qa,{artifactRegistry:artifacts}),/QA_PASS_WITH_FAILED_CHECK/)});
test('release candidate requires both fact-check and QA gates',()=>{const release={releaseId:'release:1',revision:'abc123',artifactRefs:['draft:1'],approvals:['qa-passed']};assert.throws(()=>validateArtifact('release-candidate',release,{artifactRegistry:artifacts}),/RELEASE_GATE_MISSING:fact-check-passed/)});
test('photo scout cannot pre-approve identity or rights',()=>{const media={mediaId:'m1',athleteRef:'athlete:klaebo',sourceUrl:'https://commons.wikimedia.org/wiki/File:X.jpg',license:'CC BY 4.0',width:1600,height:1200,identityReviewed:true,rightsReviewed:false};assert.throws(()=>validateArtifact('media-candidate',media,{artifactRegistry:artifacts}),/SCOUT_CANNOT_PREAPPROVE_MEDIA/)});
test('every allowed skill has exactly one provenance/risk/implementation catalog record',()=>{const catalog=loadSkillCatalog();const allowlists=JSON.parse(readFileSync('config/agents/skills.json','utf8'));const allowed=new Set(Object.values(allowlists.skills).flat());assert.equal(catalog.skills.length,allowed.size);assert.deepEqual(new Set(catalog.skills.map(s=>s.id)),allowed);for(const s of catalog.skills){assert.ok(s.origin);assert.ok(s.status);assert.ok(s.implementation);assert.ok(s.risk);assert.ok(s.review)}});
test('production publish skill exists but stays disabled until the separate auth adapter lands',()=>{const catalog=loadSkillCatalog();const publish=catalog.skills.find(s=>s.id==='production.publish');assert.equal(publish.risk,'production-write');assert.equal(publish.status,'disabled');assert.match(publish.implementation,/^disabled:/)});
