import test from 'node:test';import assert from 'node:assert/strict';
import {createJob,validateJob,assertNoSecrets} from '../lib/agents/contracts.mjs';
import {loadAgentRegistry,getAgent} from '../lib/agents/registry.mjs';
import {agentForJobType,routeJob,canDispatch,assertToolAllowed} from '../lib/agents/router.mjs';

const registry=loadAgentRegistry();const ids=new Set(registry.agents.map(a=>a.id));

test('registry has ten unique specialists and only publisher can write production',()=>{assert.equal(registry.agents.length,10);assert.equal(ids.size,10);assert.deepEqual(registry.agents.filter(a=>a.productionWrite).map(a=>a.id),['publisher'])});
test('every specialist has a prompt, model profile, retry bound and non-empty skill allowlist',()=>{for(const a of registry.agents){assert.match(a.promptPath,/^agents\/instructions\/.+\.md$/);assert.ok(['economy','balanced','expert','deterministic'].includes(a.modelProfile));assert.ok(a.maxAttempts>=1&&a.maxAttempts<=3);assert.ok(a.skills.length>0)}});
test('router sends canonical job types to the expected specialists',()=>{assert.equal(agentForJobType('source.collect'),'media-watch');assert.equal(agentForJobType('media.discover.athlete'),'photo-scout');assert.equal(agentForJobType('media.curate.athlete'),'media-curator');assert.equal(agentForJobType('research.story'),'research');assert.equal(agentForJobType('fact.article'),'fact-check');assert.equal(agentForJobType('editorial.article'),'editorial-writer');assert.equal(agentForJobType('visual.hero'),'visual-director');assert.equal(agentForJobType('qa.release'),'qa');assert.equal(agentForJobType('publish.release'),'publisher')});
test('routed jobs inherit the specialist retry ceiling and keep an audit trail',()=>{const j=createJob({type:'qa.release',agentId:'orchestrator',maxAttempts:3,inputRefs:['project:release']});const routed=routeJob(j,registry);assert.equal(routed.agentId,'qa');assert.equal(routed.maxAttempts,1);assert.equal(routed.auditTrail.at(-1).event,'job-routed');validateJob(routed,{agentIds:ids})});
test('publication cannot dispatch without fact-check and QA gates',()=>{const j=routeJob(createJob({type:'publish.release',agentId:'orchestrator',inputRefs:['release:1']}),registry);assert.deepEqual(canDispatch(j,{registry,approvals:[]}).reasons.sort(),['GATE_MISSING:fact-check-passed','GATE_MISSING:qa-passed']);assert.equal(canDispatch(j,{registry,approvals:['fact-check-passed','qa-passed']}).ok,true)});
test('named-person visuals require identity and rights review',()=>{const j=routeJob(createJob({type:'visual.hero',agentId:'orchestrator',payload:{namedPersonMedia:true},inputRefs:['media:1']}),registry);assert.equal(canDispatch(j,{registry,approvals:['identity-reviewed']}).ok,false);assert.equal(canDispatch(j,{registry,approvals:['identity-reviewed','rights-reviewed']}).ok,true)});
test('dependencies block dispatch until all upstream jobs succeeded',()=>{const j=routeJob(createJob({type:'research.story',agentId:'orchestrator',dependencies:['a','b'],inputRefs:['event:1']}),registry);assert.equal(canDispatch(j,{registry,statusByJobId:new Map([['a','succeeded'],['b','running']])}).ok,false);assert.equal(canDispatch(j,{registry,statusByJobId:new Map([['a','succeeded'],['b','succeeded']])}).ok,true)});
test('only publisher owns production mutation skill',()=>{const publisher=getAgent(registry,'publisher');assert.equal(assertToolAllowed(publisher,'production.publish',registry),true);for(const a of registry.agents.filter(a=>a.id!=='publisher'))assert.ok(!a.skills.includes('production.publish'))});
test('job payloads and audit details reject secret-bearing keys',()=>{assert.throws(()=>assertNoSecrets({authorization:'Bearer x'}),/SECRET_FIELD_FORBIDDEN/);const j=createJob({type:'research.story',agentId:'orchestrator',payload:{safe:'ok'},inputRefs:['event:1']});assert.equal(validateJob(j,{agentIds:ids}),j);assert.throws(()=>validateJob({...j,payload:{apiKey:'x'}},{agentIds:ids}),/SECRET_FIELD_FORBIDDEN/)});
test('unknown job types fail closed',()=>assert.throws(()=>agentForJobType('do-anything'),/NO_AGENT_ROUTE/));
