import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {inspectArticle,bodyDigest,sourceIds,editorialBlocks,inlineParts,editorialFilters,filterArticles,officialEditorialUrl} from '../lib/editorial-content.mjs';
const json=path=>JSON.parse(readFileSync(new URL(path,import.meta.url),'utf8'));const manifest=json('../content/editorial/manifest.json'),sources=json('../content/editorial/sources.json'),data=json('../content/editorial/season-data.json');
test('six original articles have distinct publication types and source-controlled body versions',()=>{assert.equal(manifest.length,6);assert.equal(new Set(manifest.map(m=>m.slug)).size,6);const allowed=new Set([...sources.map(s=>s.id),data.sourceId]);for(const m of manifest){assert.match(m.bodySha256,/^[a-f0-9]{64}$/);assert.ok(m.wordCount>=500);assert.ok(m.sourceIds.length>=3);assert.ok(m.sourceIds.every(id=>allowed.has(id)));assert.ok(['analysis','recap','preview'].includes(m.articleType));assert.equal(m.reviewedOn,'2026-10-03')}});
test('primary final standings, arithmetic and rank are not a fabricated podium',()=>{assert.equal(data.cupId,'BT2526SWRLCP__SMTS');assert.equal(data.status,'final');assert.equal(data.competitionCount,21);assert.equal(data.rows[0].points-data.rows[1].points,279);assert.equal(data.rows[1].points-data.rows[2].points,16);assert.equal(data.rows.find(r=>r.ibuId==='BTITA10504200001').rank,6);assert.equal(data.rows[5].points,797);assert.match(data.documentSha256,/^[a-f0-9]{64}$/)});
test('a published DB row must match reviewed content/title/dek and not be future-dated',()=>{const body='## TEST\n\nТекст [s:test]\n',meta={slug:'test',title:'Test',dek:'Dek',articleType:'analysis',bodySha256:bodyDigest(body),sourceIds:['test']};const row={slug:'test',title:'Test',dek:'Dek',article_type:'analysis',status:'published',published_at:'2026-10-03T09:00:00Z',body_md:body};const now=Date.parse('2026-10-03T10:00:00Z');assert.equal(inspectArticle(row,meta,now),true);for(const change of [{status:'draft'},{title:'Changed'},{body_md:body+'New sentence'},{published_at:'2026-10-04T00:00:00Z'}])assert.equal(inspectArticle({...row,...change},meta,now),false)});
test('unknown HTML and arbitrary links never become executable Markdown nodes',()=>{const parts=inlineParts('<script>alert(1)</script> [bad](javascript:evil) [s:source] **bold**');assert.equal(parts[0].kind,'text');assert.ok(parts[0].text.includes('<script>'));assert.deepEqual(parts.filter(p=>p.kind==='source').map(p=>p.id),['source']);assert.equal(parts.at(-1).kind,'strong');assert.equal(editorialBlocks('## Заголовок\n\n<p>unsafe</p>')[1].kind,'paragraph')});
test('heading anchors are stable and source IDs are not raw URLs',()=>{const blocks=editorialBlocks('## Первый\n\nТекст [s:a]\n\n## Второй');assert.deepEqual(blocks.filter(b=>b.kind==='heading').map(b=>b.id),['section-1','section-2']);assert.deepEqual(sourceIds('[s:a] [s:b] [s:a]'),['a','b']);assert.equal(officialEditorialUrl('https://www.biathlonworld.com/news/test')?.includes('biathlonworld'),true);for(const u of ['javascript:test','https://example.org','https://user:pass@www.biathlonworld.com/'])assert.equal(officialEditorialUrl(u),null)});
test('past recap and future preview are separate and no result is fabricated for preview',()=>{const recap=manifest.find(m=>m.articleType==='recap'),preview=manifest.find(m=>m.articleType==='preview');assert.ok(recap.eventDate<recap.reviewedOn);assert.ok(preview.eventDate>preview.reviewedOn);assert.equal(preview.stageKey,'ibu-wc-2627-kontiolahti');assert.ok(preview.takeaway.includes('не подтверждённый старт-лист'))});
test('type/athlete filters use allowlisted values, not raw database expressions',()=>{assert.equal(filterArticles(manifest,editorialFilters({type:'preview'})).length,1);assert.equal(filterArticles(manifest,editorialFilters({type:'analysis',athlete:'giacomel'})).length,2);assert.deepEqual(editorialFilters({type:['analysis'],athlete:'%sql'}),{type:'',athlete:''})});
