import {test} from 'node:test';import assert from 'node:assert/strict';
import {discoveryOptions,discoverArticles,normalizeSearch,discoveryHref} from '../lib/editorial-discovery.mjs';import {resolveReviewedRows} from '../lib/editorial-review.mjs';import {bodyDigest} from '../lib/editorial-content.mjs';
const docs=[{slug:'klaebo',title:'Клебо: три глобуса',dek:'Финиш сезона',body:'Набрано 130 очков. Tour de Ski.',athletes:['klaebo'],articleType:'analysis',sport:'cross_country',publishedAt:'2026-10-03T10:00:00Z',readMinutes:5},{slug:'biathlon',title:'Перро: итог сезона',dek:'История',body:'Проверка 130 очков [s:secret-marker]',athletes:['perrot'],articleType:'analysis',sport:'biathlon',publishedAt:'2026-10-02T10:00:00Z',readMinutes:4}];
test('aliases normalize Latin accents, ligatures and Russian spelling',()=>{assert.equal(normalizeSearch('Klæbo'),'klaebo');for(const q of ['Клэбо','Klaebo','Johannes Klæbo','КЛЕБО'])assert.equal(discoverArticles(docs,discoveryOptions({q}))[0]?.slug,'klaebo');assert.equal(normalizeSearch('Эбёрг'),normalizeSearch('Эберг'))});
test('full text is searched and source marker IDs do not become content',()=>{assert.equal(discoverArticles(docs,discoveryOptions({q:'Tour de Ski'})).length,1);assert.equal(discoverArticles(docs,discoveryOptions({q:'secret-marker'})).length,0)});
test('all words and all filters apply, impossible combination does not fall back',()=>{assert.equal(discoverArticles(docs,discoveryOptions({q:'Клебо 130'})).length,1);assert.equal(discoverArticles(docs,discoveryOptions({q:'Клебо Перро'})).length,0);assert.equal(discoverArticles(docs,discoveryOptions({q:'Клебо',sport:'biathlon'})).length,0)});
test('duplicates/oversize/empty-meaning queries are rejected rather than ignored',()=>{for(const q of [['Клебо','Перро'],'x'.repeat(121),'()[]{}',Array.from({length:13},(_,i)=>'word'+i).join(' ')]){const o=discoveryOptions({q});assert.ok(o.queryError);assert.equal(discoverArticles(docs,o).length,0)}});
test('regex and SQL-like text remain ordinary bounded strings',()=>{for(const q of ["' OR 1=1 --",'.*','<script>alert(1)</script>'])assert.equal(discoverArticles(docs,discoveryOptions({q})).length,0)});
test('sorting is explicit and stable, query relevance does not affect no-query defaults',()=>{assert.equal(discoveryOptions({}).sort,'newest');assert.equal(discoveryOptions({q:'130'}).sort,'relevance');assert.equal(discoverArticles(docs,discoveryOptions({sort:'shortest'}))[0].slug,'biathlon');assert.equal(discoverArticles(docs,discoveryOptions({sort:'__proto__'}))[0].slug,'klaebo')});
test('filter edit links only use same-origin allowlisted query keys',()=>{const url=discoveryHref(discoveryOptions({q:'Клебо & Tour',sport:'cross_country'}),{q:'',external:'https://evil.test'});assert.ok(url.startsWith('/media?'));assert.ok(!url.includes('external'));assert.ok(!url.includes('q='));assert.ok(url.includes('sport=cross_country'))});
function fixture(){const body='Текст [s:source]';const m={slug:'good',title:'Проверенный',dek:'Анонс',articleType:'analysis',sourceIds:['source'],bodySha256:bodyDigest(body)};const r={id:1,slug:m.slug,title:m.title,dek:m.dek,body_md:body,article_type:'analysis',author:'Редакция Winter Sports Hub',status:'published',published_at:'2026-10-03T09:00:00Z',updated_at:'2026-10-03T09:00:00Z'};return {m,r}}
const now=Date.parse('2026-10-03T10:00:00Z');
test('one changed body is isolated and cannot contaminate search of validated stories',()=>{const {m,r}=fixture();const m2={...m,slug:'bad'},r2={...r,id:2,slug:'bad',body_md:'Непроверенные секретные данные'};const result=resolveReviewedRows([r,r2],[m,m2],now);assert.equal(result.articles.length,1);assert.deepEqual(result.withheldSlugs,['bad']);assert.equal(result.partial,true);assert.equal(discoverArticles(result.articles,discoveryOptions({q:'секретные'})).length,0)});
test('draft/future/changed attribution and invalid dates remain withheld',()=>{const {m,r}=fixture();for(const patch of [{status:'draft'},{published_at:'2026-10-04T00:00:00Z'},{author:'Выдуманный врач'},{updated_at:'invalid'},{updated_at:'2026-10-02T00:00:00Z'}])assert.equal(resolveReviewedRows([{...r,...patch}],[m],now).articles.length,0)});
test('duplicate published slug cannot be arbitrarily selected',()=>{const {m,r}=fixture();const result=resolveReviewedRows([r,{...r,id:2}],[m],now);assert.equal(result.articles.length,0);assert.deepEqual(result.withheldSlugs,['good']);assert.throws(()=>resolveReviewedRows([r],[m,m],now),/DUPLICATE/)});
test('unknown publication is not exposed, input source array stays unchanged',()=>{const {m,r}=fixture(),input=[r,{...r,slug:'not-reviewed'}],before=JSON.stringify(input);const result=resolveReviewedRows(input,[m],now);assert.equal(result.articles.length,1);assert.equal(result.partial,false);assert.equal(JSON.stringify(input),before)});
