import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseFisDocument,seconds} from '../scripts/lib/parse-fis.mjs';
// Synthetic HTML matching observed DOM structure; no invented results are published.
function row({rank='1',bib='29',code='3190000',id='1234',name='TEST Athlete',year='1994',nation='FRA',time='2:19.83',gap='<span class="hidden-md-up visible-sm">2:19.83</span>',points='0.00'}={}){return `<a class="table-row" href="https://www.fis-ski.com/DB/general/athlete-biography.html?sectorcode=cc&amp;competitorid=${id}"><div class="g-row container"><div class="g-row justify-sb">${[rank,bib,code,name,year,`<div class="country"><span class="country__name-short">${nation}</span></div>`,time,gap,points].map(c=>`<div>${c}</div>`).join('')}</div></div></a>`}
function document(rows=row()){return `<html><head><title>FIS Results - Test (SUI) 2025/2026</title></head><body><h1>Test (SUI)</h1><div>Men's Sprint Qualification Free</div><time>December 13, 2025</time><h3>official results</h3><div id="events-info-results">${rows}</div></body></html>`}
const sourceUrl='https://www.fis-ski.com/DB/general/results.html?raceid=49485&seasoncode=2026&sectorcode=CC';
test('DOM columns preserve mixed-case names, FIS code and separate profile ID',()=>{const p=parseFisDocument(document(),{sourceUrl});assert.equal(p.rows[0].athlete,'TEST Athlete');assert.equal(p.rows[0].fis_code,'3190000');assert.equal(p.rows[0].competitor_id,'1234');assert.equal(p.metadata.gender,'men');assert.equal(p.metadata.eventDate,'2025-12-13')});
test('responsive duplicate winner time is not treated as a time gap',()=>{const r=parseFisDocument(document()).rows[0];assert.equal(r.finish_time_seconds,139.83);assert.equal(r.time_behind_seconds,0)});
test('explicit time and gap stay separate',()=>{const p=parseFisDocument(document(row()+row({rank:'2',id:'2',code:'3530000',time:'2:20.70',gap:'+0.87',points:'7.47'})));assert.equal(p.rows[1].finish_time_seconds,140.7);assert.equal(p.rows[1].time_behind_seconds,0.87)});
test('DNS/DNF/DSQ have null rank and time instead of invented results',()=>{const rows=row()+['Did not start','Did not finish','Disqualified'].map((s,i)=>`<div>${s}</div>`+row({id:String(i+20),rank:'',time:'',gap:'',points:''})).join('');const p=parseFisDocument(document(rows));assert.deepEqual(p.rows.slice(1).map(r=>r.status),['DNS','DNF','DSQ']);assert.ok(p.rows.slice(1).every(r=>r.rank===null&&r.finish_time_seconds===null))});
test('ties are allowed; duplicate athlete identities are not',()=>{const p=parseFisDocument(document(row()+row({id:'2'})));assert.equal(p.rows.length,2);assert.throws(()=>parseFisDocument(document(row()+row())),/DUPLICATE/)});
test('failed and unrelated documents are not successful empty imports',()=>{assert.throws(()=>parseFisDocument('<h1>Access denied</h1>'),/DOCUMENT_CONTRACT/);assert.throws(()=>parseFisDocument(document('')),/ROW_COVERAGE/)});
test('changed column schema fails closed',()=>assert.throws(()=>parseFisDocument(document(row().replace('</div></div></a>','<div>extra</div></div></div></a>'))),/COLUMN_CONTRACT/));
test('a historical result cannot satisfy a current-season contract',()=>assert.throws(()=>parseFisDocument(document(),{sourceUrl,expected:{season:'2027'}}),/IDENTITY_MISMATCH_SEASON/));
test('untrusted source host is rejected',()=>assert.throws(()=>parseFisDocument(document(),{sourceUrl:'https://attacker.example/DB/general/results.html?raceid=1'}),/SOURCE_INVALID/));
test('invalid and malformed time values rejected',()=>{for(const v of [null,'','abc','1:60','-3','NaN','1:2:3:4','2:19.8321'])assert.equal(seconds(v),null);assert.equal(seconds('1:02:03.5'),3723.5);assert.equal(seconds('+12.3'),12.3)});
