import {test} from 'node:test';import assert from 'node:assert/strict';import {parseFlgrProgramme,compareProgramme} from '../scripts/lib/flgr-programme.mjs';
const doc=(line='26.11 - Классический стиль, 10/10 км')=>`<html><body><h1>ФосАгро Кубок России по лыжным гонкам 2026-2027!</h1><p>Проект Календаря<br>I Этап Кубка России<br>пгт. Вершина Теи<br>${line}<br>Все новости</p></body></html>`;
const baseline={season:'2026/27',certainty:'provisional',sourceUrl:'https://flgr.ru/news/example/',rows:[['1','2026-11-26','Классический стиль, 10/10 км']]};
test('reads source date and programme, never infers start time or gender',()=>{const p=parseFlgrProgramme(doc());assert.deepEqual(p.rows,baseline.rows);assert.equal(p.certainty,'provisional');assert.equal('start_time_msk' in p,false)});
test('unchanged data creates no notification or proposal',()=>{const diff=compareProgramme(baseline,parseFlgrProgramme(doc()));assert.equal(diff.requiresAttention,false);assert.equal(diff.mayPublish,false)});
test('new date does not silently cancel the previous race',()=>{const d=compareProgramme(baseline,parseFlgrProgramme(doc('28.11 - Классический стиль, 10/10 км')));assert.equal(d.changes.length,2);assert.ok(d.changes.some(c=>c.kind==='missing_from_source_not_cancellation'));assert.ok(d.changes.every(c=>c.status==='pending_review'))});
test('identical changes produce stable keys independent of check time',()=>assert.equal(compareProgramme(baseline,parseFlgrProgramme(doc('28.11 - Спринт'))).fingerprint,compareProgramme(baseline,parseFlgrProgramme(doc('28.11 - Спринт'))).fingerprint));
test('wrong season, empty source and unsupported status fail closed',()=>{assert.throws(()=>parseFlgrProgramme(doc().replaceAll('2026-2027','2025-2026')),/SEASON/);assert.throws(()=>parseFlgrProgramme(doc().replace('Проект Календаря','Утверждено')),/CERTAINTY/);assert.throws(()=>parseFlgrProgramme(doc('нет гонок')),/EMPTY/)});
test('untrusted scripts never enter programme data',()=>{const p=parseFlgrProgramme(doc()+'<script>delete everything;26.11 - bad</script>');assert.deepEqual(p.rows,baseline.rows)});
