import {test} from 'node:test';import assert from 'node:assert/strict';
import {dateEvidence,normalize,delta,timestamp,syndication} from '../scripts/media-watch/model.mjs';import {mediaIndex} from '../scripts/media-watch/parsers.mjs';
const source={key:'sports-skiing',adapter:'sports_index',sport:'cross_country',kind:'media',url:'https://www.sports.ru/skiing/',fetchUrl:'https://www.sports.ru/skiing/'};
test('date-only and unzoned time retain date but never invent UTC or Moscow',()=>{assert.deepEqual(dateEvidence('2026-10-02'),{publishedAt:null,publishedDate:'2026-10-02',timeWarning:null});assert.equal(dateEvidence('2026-10-02T17:15:00').publishedAt,null);assert.equal(dateEvidence('2026-10-02T17:15:00').timeWarning,'SOURCE_TIMEZONE_NOT_GIVEN');assert.equal(timestamp('2026-02-30T10:00:00Z'),null)});
test('unresolved index date is explicit instead of dropping all valid article links',()=>{const p=mediaIndex('<title>Sports.ru</title><article><time datetime="2026-10-02"></time><a href="/biathlon/15.html">Тестовый заголовок о программе соревнований</a></article>',source);assert.equal(p.rows.length,1);assert.equal(p.rows[0].publishedDate,'2026-10-02');assert.equal(p.rows[0].publishedAt,null)});
test('sensitive biographical stories get generic review title; alpine news is outside scope',()=>{const row={externalId:'15',url:'https://www.sports.ru/skiing/15.html',text:'Лыжница скоро станет мамой',publishedAt:null};assert.equal(normalize(row,source,{}).item.sensitive,true);assert.equal(normalize({...row,text:'Линдси Вонн выступит в горнолыжном спорте'},source,{}).skip,'unrelated_sport')});
test('two independent index sources are not confused as a revision of one another',()=>{const common={url:'https://www.sports.ru/skiing/15.html',revision:'a'.repeat(64)},old={parserVersion:'v1',configHash:'a',sources:[],items:[{...common,sourceKey:'index'}]},next={...old,items:[...old.items,{...common,sourceKey:'rss',revision:'b'.repeat(64)}]};assert.equal(delta(old,next).changedReferences.length,0);assert.equal(delta(old,next).newReferences.length,1);assert.equal(delta(old,{...next,parserVersion:'v2'}).baselineAvailable,false)});
test('changed versions detected but counters/receipt changes do not count',()=>{const i={url:'https://t.me/test/1',sourceKey:'one',revision:'a'.repeat(64)};const old={sources:[],items:[i]},next={sources:[],items:[{...i,revision:'b'.repeat(64)}]};assert.equal(delta(old,next).changedReferences.length,1)});
test('forward loops do not mint a false original source',()=>{const a={url:'https://t.me/a/1',forwardedFrom:'https://t.me/b/1',mediaOnly:true},b={url:'https://t.me/b/1',forwardedFrom:'https://t.me/a/1',mediaOnly:true};assert.deepEqual(syndication([a,b]),[])});
