import Link from 'next/link';import {ArrowUpRight,Bookmark,CalendarDays,Target,Mountain} from 'lucide-react';
import {SiteNav} from '../components/SiteNav';import {RaceList} from '../components/RaceList';import {StageCard} from '../components/stages/StageCard';import {SaveButton} from '../components/personal/SaveButton';import {GuideCards} from '../components/GuideCards';import {FeaturedProgramme} from '../components/home/FeaturedProgramme';import {LatestEditorial} from '../components/editorial/LatestEditorial';import {FullscreenHero} from '../components/visual/FullscreenHero';
import {getStageCatalogue} from '../lib/stage-data';import {homeSeason} from '../lib/home-season.mjs';import {stagePlace,stageDateRange,stageSeries,stageCountry} from '../lib/stage-catalog.mjs';import {moscowDate} from '../lib/domain.mjs';import {guides} from '../lib/guides';import {pageMetadata} from '../lib/seo';import styles from '../components/home/Home.module.css';import visual from '../components/visual/FullScreen.module.css';
export const dynamic='force-dynamic';
export const metadata=pageMetadata('Биатлон и лыжные гонки 2026–2027: календарь и мой сезон','Реальные истории спортсменов, программы этапов, гонки по дням и первоисточники. Россия и международные соревнования.','/');
export default async function Home(){
 const data=await getStageCatalogue();const snapshot=homeSeason(data.models,moscowDate());const featured=snapshot.stage;const c=featured?.competition;
 return <main id="main-content" className={visual.home}><div className={visual.navFrame}><SiteNav/></div><FullscreenHero/><div className={visual.content} id="season-content"><div className={visual.archiveLink}><span>Фотохроника зимнего спорта</span><Link href="/athletes">Лица зимы — весь фотоархив ↗</Link></div>
  <div className={styles.hero}><div><div className={styles.season}>ВАШ КАЛЕНДАРЬ · 2026/27</div><h2 style={{fontSize:'clamp(32px,4vw,54px)',lineHeight:1.1,letterSpacing:'-.035em'}}>Следующий старт.<br/>Всё, что нужно знать.</h2><p>Программа, время по Москве и официальные ссылки. Сохраните гонки, за которыми хотите следить.</p><div className={styles.buttons}><Link className={styles.primary} href="/calendar">Календарь гонок <ArrowUpRight size={18} aria-hidden="true"/></Link><Link href="/media">Истории и аналитика →</Link></div></div>
   {c?<article className={styles.spotlight}><small>БЛИЖАЙШИЙ ЭТАП</small><h2><Link href={`/competitions/${c.id}`}>{stagePlace(c)}</Link></h2><p>{stageSeries(c.series)} · {stageCountry(c)}</p><div className={styles.date}><CalendarDays size={19} aria-hidden="true"/>{stageDateRange(c.start_date,c.end_date)}</div><FeaturedProgramme summary={featured.summary}/><div className={styles.featureTools}><Link href={`/competitions/${c.id}`}>Смотреть программу <ArrowUpRight size={17} aria-hidden="true"/></Link><SaveButton kind="stage" id={c.id} label={stagePlace(c)}/></div></article>:<article className={styles.spotlight}><h2>{data.unavailable?'Календарь временно недоступен':'Сезон в архиве'}</h2><p>{data.unavailable?'Не удалось получить опубликованные этапы. Данные не заменяются демонстрационными.':'Ближайших опубликованных этапов этой выборки больше нет. Программы и источники остаются доступны.'}</p><Link href="/competitions">Открыть каталог →</Link></article>}
  </div>
  <nav className={styles.directions} aria-label="Выбрать направление">{[['biathlon','international','Биатлон','Международные'],['biathlon','russia','Биатлон','Россия'],['cross_country','international','Лыжные гонки','Международные'],['cross_country','russia','Лыжные гонки','Россия']].map(([sport,scope,title,region])=>{const Icon=sport==='biathlon'?Target:Mountain;return <Link className={styles.direction} href={`/competitions?sport=${sport}&scope=${scope}`} key={sport+scope}><Icon size={23} aria-hidden="true"/><span><strong>{title}</strong>{region}</span></Link>})}</nav>
  <div className={styles.schedule}><section><div className={styles.sectionHead}><h2>{snapshot.showsLater?'Следующие старты':'Ближайшая неделя'}</h2><Link href="/calendar">Все гонки →</Link></div><nav className={styles.periods} aria-label="Быстрый выбор периода"><Link href="/calendar?when=today">Сегодня</Link><Link href="/calendar?when=tomorrow">Завтра</Link><Link href="/calendar?when=week">7 дней</Link></nav>{snapshot.showsLater&&<p className={styles.note}>На ближайшие семь дней в базе нет неотменённых гонок. Ниже показаны следующие даты, а не сегодняшние старты.</p>}<RaceList races={snapshot.races} unavailable={data.unavailable||data.programmeUnavailable}/></section><aside><article className={styles.invitation}><Bookmark size={25} aria-hidden="true"/><h2>Ваш личный<br/>маршрут сезона.</h2><p>Сохраняйте целые этапы и отдельные гонки. Сохранённое доступно в этом браузере без регистрации.</p><Link href="/my-season">Открыть «Мой сезон» <ArrowUpRight size={17} aria-hidden="true"/></Link></article></aside></div>
  <LatestEditorial/>
  {snapshot.stages.length>0&&<section className={styles.stageSection}><div className={styles.sectionHead}><h2>Ближайшие этапы</h2><Link href="/competitions">Весь сезон →</Link></div><div className={styles.stageGrid}>{snapshot.stages.map(model=><StageCard model={model} key={model.competition.id}/>)}</div></section>}
  <section className={styles.guideSection}><div className={styles.sectionHead}><h2>Гид по зимнему спорту.</h2><Link href="/guides">Гид зрителя →</Link></div><GuideCards items={guides.filter(g=>['kak-chitat-kalendar','start-list-i-rezultaty'].includes(g.slug))}/></section>

 </div></main>;
}
