import Link from 'next/link';
import {SiteNav} from '../components/SiteNav';
import {RaceList} from '../components/RaceList';
import {CompetitionList} from '../components/CompetitionList';
import {RecentChanges} from '../components/RecentChanges';
import {getRaces,getCompetitions} from '../lib/data';
import {moscowDate} from '../lib/domain.mjs';
import {calendarWindow} from '../lib/calendar-window.mjs';
import {pageMetadata} from '../lib/seo';
export const dynamic='force-dynamic';
export const metadata=pageMetadata('Биатлон и лыжные гонки 2026–2027: календарь и этапы','Гонки сегодня, завтра и на ближайшей неделе. Программа этапов, первоисточники, статусы и проверенные трансляции.','/');
export default async function Home(){const range=calendarWindow('week');const [week,stages]=await Promise.all([getRaces({from:range.from,to:range.to,limit:50}),getCompetitions({from:moscowDate(),limit:3})]);const next=!week.unavailable&&!week.races.length?await getRaces({from:range.from,limit:6}):null;return <main id="main-content"><SiteNav/><header className="seasonHero"><div className="eyebrow">WINTER SPORTS HUB · СЕЗОН 2026/27</div><h1>Весь сезон.<br/><span className="outlineText">Без догадок.</span></h1><p className="lead">Биатлон и лыжные гонки. От программы этапа до конкретного старта — с источником и понятным статусом.</p><div className="heroLinks"><Link className="primaryLink" href="/calendar">Открыть календарь ↗</Link><Link href="/competitions">Этапы сезона →</Link></div></header><nav className="periodNav" aria-label="Быстрый выбор периода"><Link href="/calendar?when=today">Сегодня</Link><Link href="/calendar?when=tomorrow">Завтра</Link><Link href="/calendar?when=week">Ближайшие 7 дней</Link><Link href="/calendar">Весь сезон</Link></nav><div className="grid"><section><div className="sectionHead"><div><small>{next?'ЗА ПРЕДЕЛАМИ БЛИЖАЙШЕЙ НЕДЕЛИ':'БЛИЖАЙШАЯ НЕДЕЛЯ'}</small><h2>{next?'Следующие опубликованные гонки':'Старты недели'}</h2></div></div>{next&&<p className="metricNote">На ближайшие семь дней в базе нет опубликованных гонок. Ниже — следующие старты, а не расписание на сегодня.</p>}<RaceList {...(next||week)}/></section><aside><RecentChanges/><article className="panel"><h2>Два вида спорта</h2><div className="stackLinks"><Link href="/biathlon">Биатлон →</Link><Link href="/cross-country">Лыжные гонки →</Link><Link href="/data-health">Состояние данных →</Link></div></article></aside></div><section><h2>Ближайшие этапы</h2><p className="metricNote">Этап может быть опубликован раньше программы отдельных гонок.</p><CompetitionList {...stages}/></section></main>}
