import {SiteNav} from '../components/SiteNav';
import { supabase } from '../lib/supabase';

type Race={id:number;event_date:string|null;start_time_msk:string|null;sport:string;scope:string;gender:string;series:string;location:string|null;country:string|null;discipline:string;distance:string|null;broadcaster:string|null;stream_url:string|null;status:string};

const fallback:Race[]=[
{id:1,event_date:'2026-11-28',start_time_msk:'12:30',sport:'biathlon',scope:'international',gender:'women',series:'Кубок мира',location:'Контиолахти',country:'Финляндия',discipline:'Индивидуальная гонка',distance:'15 км',broadcaster:'Проверяем эфир',stream_url:null,status:'scheduled'},
{id:2,event_date:'2026-11-28',start_time_msk:'16:15',sport:'biathlon',scope:'international',gender:'men',series:'Кубок мира',location:'Контиолахти',country:'Финляндия',discipline:'Индивидуальная гонка',distance:'20 км',broadcaster:'Проверяем эфир',stream_url:null,status:'scheduled'},
{id:3,event_date:'2026-11-29',start_time_msk:'13:00',sport:'cross_country',scope:'international',gender:'women',series:'Кубок мира',location:'Рука',country:'Финляндия',discipline:'Спринт · классический стиль',distance:null,broadcaster:'Проверяем эфир',stream_url:null,status:'scheduled'}];

const sex=(g:string)=>g==='men'?'М':g==='women'?'Ж':'МИКСТ';
const sport=(s:string)=>s==='biathlon'?'БИАТЛОН':'ЛЫЖИ';
const date=(v:string|null)=>v?new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',timeZone:'Europe/Moscow'}).format(new Date(v+'T12:00:00+03:00')).toUpperCase():'ДАТА';
const time=(v:string|null)=>v?v.slice(0,5):'—';

export default async function Home(){
 const {data}=await supabase.from('events').select('*').gte('event_date','2026-10-01').lte('event_date','2027-05-31').not('id','in','(1,2,3)').order('event_date').order('start_time_msk').limit(12);
 const races=(data?.length?data:fallback) as Race[];
 return <main><SiteNav/><header><div className="eyebrow">WINTER SPORTS HUB · 2026/27</div><h1>Сезон — в одном месте.</h1><p className="lead">Биатлон и лыжные гонки. Московское время, трансляции, изменения расписания, превью и разбор каждой гонки.</p><nav><button className="active">Сегодня</button><button>Календарь</button><button>Race Center</button><button>Аналитика</button></nav></header><section className="ticker"><span className="live">● LIVE INTELLIGENCE</span><span>IBU · FIS · СБР · ФЛГР</span><span>Расписание синхронизируется с базой</span></section><div className="grid"><section><div className="sectionHead"><div><small>БЛИЖАЙШИЕ СТАРТЫ</small><h2>Смотреть дальше</h2></div><div className="filters"><button>Все</button><button>Биатлон</button><button>Лыжи</button></div></div><div className="races">{races.map(r=><article className={'race '+(r.sport==='cross_country'?'ski':'bio')} key={r.id}><div className="date"><b>{date(r.event_date)}</b><span>{time(r.start_time_msk)} МСК</span></div><div className="raceMain"><div className="tags"><i>{sport(r.sport)}</i><i>{sex(r.gender)}</i><i>{r.scope==='russia'?'РФ':'МИР'}</i></div><h3>{r.discipline}{r.distance?' · '+r.distance:''}</h3><p>{r.series} · {r.location}{r.country?' · '+r.country:''}</p></div><div className="actions"><button>Race Center →</button>{r.stream_url?<a href={r.stream_url}>Смотреть эфир</a>:<a>{r.broadcaster||'Эфир уточняется'}</a>}</div></article>)}</div></section><aside><div className="panel hero"><small>RACE INTELLIGENCE</small><h2>До старта</h2><p>Старт-лист, форма спортсменов, трасса, погода и новости будут собираться в единое превью с указанием источников.</p><div className="stat"><b>4</b><span>первичных источника<br/>под контролем</span></div></div><div className="panel"><small>АВТОМАТИЗАЦИЯ</small><ul><li><b>01</b> Расписание и изменения</li><li><b>02</b> Трансляции и ссылки</li><li><b>03</b> Погода + старт-листы</li><li><b>04</b> Превью → результаты → разбор</li></ul></div></aside></div></main>
}