import Link from 'next/link';
import type {Race} from '../lib/data';
import {formatDate,genderLabel,raceStatus,safeHttpsUrl,sportLabel} from '../lib/domain.mjs';
export function RaceList({races,unavailable=false}:{races:Race[];unavailable?:boolean}){
 if(unavailable)return <div className="emptyState" role="status"><h2>Расписание временно недоступно</h2><p>Не удалось получить данные. Демонстрационные гонки не подставляются.</p><Link href="/sources">Первоисточники →</Link></div>;
 if(!races.length)return <div className="emptyState"><h2>В этом разделе пока нет опубликованных гонок</h2><p>Отсутствие записи в базе не означает отмену. Проверьте этапы и первоисточники.</p><Link href="/competitions">Посмотреть этапы →</Link></div>;
 return <div className="races">{races.map(r=><article className={'race '+(r.sport==='cross_country'?'ski':'bio')} key={r.id}><div className="date"><b>{formatDate(r.event_date)}</b><span>{r.start_time_msk?`${r.start_time_msk.slice(0,5)} МСК`:'Время не опубликовано'}</span></div><div className="raceMain"><div className="tags"><i>{sportLabel(r.sport)}</i><i>{genderLabel(r.gender)}</i><i>{r.scope==='russia'?'Россия':'Международные'}</i></div><h3><Link href={`/race-center/${r.id}`}>{r.discipline}{r.distance?' · '+r.distance:''}</Link></h3><p>{r.series} · {r.location||'Место уточняется'}{r.country?' · '+r.country:''}</p><span className={'status '+r.status}>{raceStatus(r.status)}</span></div><div className="actions"><Link className="watchButton" href={`/race-center/${r.id}`}>О гонке →</Link>{r.competition_id&&<Link href={`/competitions/${r.competition_id}`}>Весь этап →</Link>}{safeHttpsUrl(r.source_url)&&<a href={safeHttpsUrl(r.source_url)!} target="_blank" rel="noopener noreferrer">Первоисточник ↗</a>}</div></article>)}</div>;
}
export function RaceFilters({sport,scope,when}:{sport?:string;scope?:string;when?:string}){return <form action="/calendar" method="get" className="raceFilters"><label>Вид спорта<select name="sport" defaultValue={sport||''}><option value="">Все виды</option><option value="biathlon">Биатлон</option><option value="cross_country">Лыжные гонки</option></select></label><label>Серия<select name="scope" defaultValue={scope||''}><option value="">Все серии</option><option value="russia">Россия</option><option value="international">Международные</option></select></label><label>Период<select name="when" defaultValue={when||'season'}><option value="season">Весь сезон</option><option value="today">Сегодня</option><option value="tomorrow">Завтра</option><option value="week">Ближайшие 7 дней</option></select></label><button type="submit">Показать</button><Link href="/calendar">Сбросить</Link></form>}
