import {test,expect} from '@playwright/test';import {mkdirSync} from 'node:fs';import photos from '../content/visual/athletes.json';
test('photograph stays unwarped through scene changes and links to its actual original',async({page},info)=>{
 await page.goto('/');const hero=page.locator('[data-fullscreen-hero]');
 for(const p of photos){await hero.getByRole('button',{name:`Показать: ${p.name}`,exact:true}).click();const image=hero.locator('img'),layer=hero.locator('[data-star-photo]');await expect.poll(()=>image.evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true);await expect(layer).toHaveAttribute('data-original-sha256',p.sourceSha256);await expect(layer).toHaveCSS('transform','none');await expect(image).toHaveCSS('filter','none');await expect(image).toHaveCSS('transform','none');await expect(hero.getByRole('link',{name:'Открыть исходный кадр ↗',exact:true})).toHaveAttribute('href',p.originalUrl);if(!p.highResolution){for(let n=0;n<5;n++){expect((await image.boundingBox())!.width).toBeLessThanOrEqual(p.originalWidth);await page.waitForTimeout(100)}}}
 mkdirSync('artifacts/screenshots',{recursive:true});await page.screenshot({path:`artifacts/screenshots/${info.project.name}-authentic-small-portrait.png`,fullPage:false});
});
test('an early broken-image event is recognized after hydration, without a replacement face',async({page})=>{
 await page.route('**/athletes/laegreid-*.webp',r=>r.fulfill({status:200,contentType:'image/webp',body:'not-an-image'}));await page.goto('/');const hero=page.locator('[data-fullscreen-hero]');await expect(hero.locator('[data-star-photo]')).toHaveAttribute('data-photo-failed','true');await expect(hero).toContainText('Фотография временно недоступна');await expect(hero.locator('img')).toHaveCount(1);await hero.getByRole('button',{name:'Показать: Йоханнес Клебо',exact:true}).click();await expect.poll(()=>hero.locator('img').evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true);await expect(hero.locator('[data-star-photo]')).toHaveAttribute('data-photo-failed','false');
});
