import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';
test('home is usable, has no hydration errors or horizontal overflow',async({page},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('h1')).toContainText('Весь сезон.');await expect(page.locator('main')).toBeVisible();
 // Responsive navigation has a hidden alternative tree; verify the accessible calendar link, not the first hidden DOM anchor.
 await expect(page.getByRole('link',{name:'Календарь',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.emulateMedia({reducedMotion:'reduce'});mkdirSync('artifacts/screenshots',{recursive:true});await page.screenshot({path:`artifacts/screenshots/${info.project.name}-home.png`,fullPage:false});expect(errors).toEqual([])});
test('calendar filters really submit and display matching races',async({page},info)=>{await page.goto('/calendar');await page.locator('select[name="sport"]').selectOption('cross_country');await page.locator('select[name="scope"]').selectOption('international');await page.getByRole('button',{name:'Показать',exact:true}).click();await expect(page).toHaveURL(/sport=cross_country.*scope=international/);await expect(page.locator('.race').first()).toBeVisible();await expect(page.locator('.race').first()).toContainText('Лыжные гонки');await expect(page.locator('.race').first()).toContainText('Международные');expect(await page.locator('.race').count()).toBeGreaterThan(0);await expect(page.locator('.race').filter({hasText:'Биатлон'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`artifacts/screenshots/${info.project.name}-calendar.png`,fullPage:false});await page.locator('.race h3 a').first().click();await expect(page).toHaveURL(/\/race-center\/\d+$/);await expect(page.getByRole('heading',{name:'Трансляция',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:/Открыть первоисточник/})).toHaveAttribute('href',/^https:\/\//)});
test('legacy unsourced race is not a public page',async({request})=>{const response=await request.get('/race-center/1');expect(response.status()).toBe(404)});
test('competition projects are explicitly labelled',async({page})=>{await page.goto('/competitions');await expect(page.getByText('Проект календаря',{exact:true}).first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)});
test('keyboard skip link resolves to a real focus target',async({page})=>{await page.goto('/methodology');await page.keyboard.press('Tab');await expect(page.locator('.skipLink')).toBeFocused();await page.keyboard.press('Enter');await expect(page).toHaveURL(/#site-content$/);await expect(page.locator('#site-content')).toBeFocused()});
test('uploads stay disabled and preview stays noindex',async({page,request})=>{const response=await request.post('/api/media/upload-ticket');expect(response.status()).toBe(503);expect((await response.json()).error).toBe('MEDIA_UPLOADS_DISABLED');await page.goto('/legal');await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content',/noindex/);await expect(page.getByRole('heading',{level:1})).toHaveCount(1)});
