import {createHash} from 'node:crypto';
export const bodyDigest=body=>createHash('sha256').update(body).digest('hex');
export function sourceIds(body){return [...new Set([...body.matchAll(/\[s:([a-z0-9-]+)\]/g)].map(m=>m[1]))]}
export function inspectArticle(row,manifest,now=Date.now()){if(!row||!manifest||row.slug!==manifest.slug||row.status!=='published'||typeof row.body_md!=='string'||row.body_md.length>80000)return false;const time=Date.parse(row.published_at||'');if(!Number.isFinite(time)||time>now)return false;if(row.title!==manifest.title||row.dek!==manifest.dek||row.article_type!==manifest.articleType||bodyDigest(row.body_md)!==manifest.bodySha256)return false;const cited=sourceIds(row.body_md);if(cited.length!==manifest.sourceIds.length||cited.some(id=>!manifest.sourceIds.includes(id)))return false;return true;}
export function editorialBlocks(body){if(typeof body!=='string'||body.length>80000)throw new Error('ARTICLE_SIZE');let count=0;return body.split(/\n\s*\n/).map(t=>t.trim()).filter(Boolean).map(raw=>{const h=raw.match(/^(#{2,3})\s+([^\n]+)$/);return h?{kind:'heading',level:h[1].length,id:'section-'+(++count),text:h[2]}:{kind:'paragraph',text:raw.replace(/\n/g,' ')}})}
export function inlineParts(value){const parts=[];let from=0;for(const m of value.matchAll(/\[s:([a-z0-9-]+)\]|\*\*([^*\n]+)\*\*/g)){if(m.index>from)parts.push({kind:'text',text:value.slice(from,m.index)});parts.push(m[1]?{kind:'source',id:m[1]}:{kind:'strong',text:m[2]});from=m.index+m[0].length;}if(from<value.length)parts.push({kind:'text',text:value.slice(from)});return parts}
export function editorialFilters(params={}){const one=(k,values)=>typeof params[k]==='string'&&values.includes(params[k])?params[k]:'';const result={type:one('type',['analysis','recap','preview']),athlete:one('athlete',['perrot','laegreid','giacomel','botn','samuelsson','jacquelin','jeanmonnot','hanna-oeberg','vittozzi','elvira-oeberg','minkkinen','simon','klaebo','amundsen','diggins','ilar','dahlqvist'])};const sport=one('sport',['biathlon','cross_country']);return sport?{...result,sport}:result}
export function filterArticles(items,filters){return items.filter(a=>(!filters.type||a.articleType===filters.type)&&(!filters.athlete||a.athletes.includes(filters.athlete))&&(!filters.sport||(a.sport||'biathlon')===filters.sport))}
export function officialEditorialUrl(value){try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port||!['www.biathlonworld.com','biathlonresults.com','www.biathlonresults.com','kontiolahtibiathlon.com','www.fis-ski.com'].includes(u.hostname))return null;return u.href}catch{return null}}
