// Pure computations on a frozen, reviewed historical dataset. No live API, inferred starts or invented points.
export const phaseLabel={december:'Декабрь · 8 гонок',january:'Январь · 6 гонок',march:'Март · 7 гонок',all:'Весь Кубок мира · 21 гонка'};
export const disciplineLabel={IN:'Индивидуальная гонка',SI:'Короткая индивидуальная',SP:'Спринт',PU:'Преследование',MS:'Масс-старт'};
export const venueLabel={Oestersund:'Эстерсунд',Hochfilzen:'Хохфильцен','Annecy-Le Grand Bornand':'Ле-Гран-Борнан',Oberhof:'Оберхоф',Ruhpolding:'Рупольдинг','Nove Mesto na Morave':'Нове-Место',Kontiolahti:'Контиолахти',Otepaa:'Отепя','Oslo Holmenkollen':'Осло'};
const validDate=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value+'T12:00:00Z'))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value;
export function validateLedger(data){
 if(data?.schemaVersion!==1||data.cupId!=='BT2526SWRLCP__SMTS'||data.season!=='2025/26'||data.races?.length!==21||data.athletes?.length!==6)throw new Error('LEDGER_SCOPE');
 const ids=new Set(),keys=new Set(data.athletes.map(a=>a.key));if(keys.size!==6)throw new Error('ATHLETE_IDENTITY');let prev='';
 for(const race of data.races){if(!/^BT2526SWRLCP0[1-9]SM(IN|SI|SP|PU|MS)$/.test(race.raceId)||ids.has(race.raceId)||!race.raceId.endsWith('SM'+race.discipline)||!validDate(race.date)||race.date<prev||race.results?.length!==6||![2,4].includes(race.shootings)||race.shootings!==(race.discipline==='SP'?2:4)||!Number.isInteger(race.sourceRows)||race.sourceRows<30||!Number.isFinite(Date.parse(race.fetchedAt))||!/^[a-f0-9]{64}$/.test(race.documentSha256))throw new Error('RACE_CONTRACT');ids.add(race.raceId);prev=race.date;
  for(const row of race.results){if(row===null)continue;if(!Array.isArray(row)||row.length!==3||!Number.isInteger(row[0])||row[0]<1||!Number.isInteger(row[1])||row[1]<0||row[1]>90||typeof row[2]!=='string')throw new Error('RESULT_CONTRACT');const bouts=row[2].split('+');if(bouts.length!==race.shootings||bouts.some(v=>! /^[0-5]$/.test(v)))throw new Error('SHOOTING_CONTRACT');}
 }
 for(let i=0;i<6;i++){const sum=data.races.reduce((n,r)=>n+(r.results[i]?.[1]??0),0);if(sum!==data.athletes[i].finalPoints)throw new Error('FINAL_TOTAL_MISMATCH');}return true;
}
export function sourceUrl(raceId){if(!/^BT2526SWRLCP0[1-9]SM(IN|SI|SP|PU|MS)$/.test(raceId))throw new Error('RACE_URL_ID');return 'https://biathlonresults.com/modules/sportapi/api/Results?RaceId='+raceId;}
export function phaseRaces(data,phase='all'){if(!Object.hasOwn(phaseLabel,phase))throw new Error('PHASE');return data.races.filter(r=>phase==='all'||phase==='december'&&r.date.startsWith('2025-12')||phase==='january'&&r.date.startsWith('2026-01')||phase==='march'&&r.date.startsWith('2026-03'));}
export function athleteStats(data,key,phase='all'){
 const index=data.athletes.findIndex(a=>a.key===key);if(index<0)throw new Error('ATHLETE');const races=phaseRaces(data,phase),rows=races.map(r=>r.results[index]).filter(r=>r!==null),ranked=rows.map(r=>r[0]).sort((a,b)=>a-b);
 const finishes=rows.length,points=rows.reduce((n,r)=>n+r[1],0),podiumPoints=rows.filter(r=>r[0]<=3).reduce((n,r)=>n+r[1],0);
 return {key,points,finishes,notListed:races.length-finishes,wins:rows.filter(r=>r[0]===1).length,podiums:rows.filter(r=>r[0]<=3).length,top5:rows.filter(r=>r[0]<=5).length,top10:rows.filter(r=>r[0]<=10).length,podiumPoints,otherPoints:points-podiumPoints,medianRank:finishes?(ranked[Math.floor((finishes-1)/2)]+ranked[Math.floor(finishes/2)])/2:null,meanPoints:finishes?points/finishes:null};
}
export function comparison(data,left,right){const li=data.athletes.findIndex(a=>a.key===left),ri=data.athletes.findIndex(a=>a.key===right);if(li<0||ri<0)throw new Error('ATHLETE');let a=0,b=0;return data.races.map((r,i)=>{const l=r.results[li],rr=r.results[ri];a+=l?.[1]??0;b+=rr?.[1]??0;return {index:i+1,raceId:r.raceId,date:r.date,venue:r.venue,discipline:r.discipline,left:l,right:rr,leftTotal:a,rightTotal:b,gap:a-b};});}
const cell=value=>{const s=String(value??'');return '"'+(/^[=+\-@\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')+'"'};
export function ledgerCsv(data){validateLedger(data);const rows=[['season','race_id','date','venue','discipline','athlete','ibu_id','state','rank','world_cup_points','misses_per_bout','source_url','source_sha256','fetched_at']];for(const race of data.races)for(let i=0;i<data.athletes.length;i++){const a=data.athletes[i],r=race.results[i];rows.push([data.season,race.raceId,race.date,race.venue,race.discipline,a.name,a.ibuId,r?'classified':'not_in_result_table',r?.[0]??'',r?.[1]??0,r?.[2]??'',sourceUrl(race.raceId),race.documentSha256,race.fetchedAt]);}return '\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')+'\r\n';}
