// Reviewed historical datasets only. Keep classification, explicit DNS and absence distinct.
export const phaseLabel={december:'Декабрь · 8 гонок',january:'Январь · 6 гонок',march:'Март · 7 гонок',all:'Весь Кубок мира · 21 гонка'};
export const disciplineLabel={IN:'Индивидуальная гонка',SI:'Короткая индивидуальная',SP:'Спринт',PU:'Преследование',MS:'Масс-старт'};
export const venueLabel={Oestersund:'Эстерсунд',Hochfilzen:'Хохфильцен','Annecy-Le Grand Bornand':'Ле-Гран-Борнан',Oberhof:'Оберхоф',Ruhpolding:'Рупольдинг','Nove Mesto na Morave':'Нове-Место',Kontiolahti:'Контиолахти',Otepaa:'Отепя','Oslo Holmenkollen':'Осло'};
const validDate=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
export function categoryOf(data){if(data.cupId==='BT2526SWRLCP__SMTS')return 'SM';if(data.cupId==='BT2526SWRLCP__SWTS')return 'SW';throw new Error('LEDGER_SCOPE')}
export function resultState(race,index){return race.states?.[index]||(race.results[index]===null?'not_listed':'classified')}
export function validateLedger(data){
 const category=categoryOf(data),women=category==='SW';
 if(data.schemaVersion!==(women?2:1)||women&&data.category!=='SW'||!women&&data.category&&data.category!=='SM'||data.season!=='2025/26'||data.races?.length!==21||data.athletes?.length!==6)throw new Error('LEDGER_SCOPE');
 const identity=new RegExp('^BT[A-Z]{3}'+(women?'2':'1')+'[0-9]{10}$');const keys=new Set(),athletes=new Set();
 for(const a of data.athletes){if(!/^[a-z-]+$/.test(a.key)||!identity.test(a.ibuId)||keys.has(a.key)||athletes.has(a.ibuId)||!Number.isInteger(a.finalPoints)||a.finalPoints<0)throw new Error('ATHLETE_IDENTITY');keys.add(a.key);athletes.add(a.ibuId)}
 const ids=new Set(),pattern=new RegExp('^BT2526SWRLCP0[1-9]'+category+'(IN|SI|SP|PU|MS)$');let prev='';
 for(const race of data.races){if(!pattern.test(race.raceId)||ids.has(race.raceId)||!race.raceId.endsWith(category+race.discipline)||!validDate(race.date)||race.date<prev||race.results?.length!==6||race.shootings!==(race.discipline==='SP'?2:4)||!Number.isInteger(race.sourceRows)||race.sourceRows<30||!Number.isFinite(Date.parse(race.fetchedAt))||!/^[a-f0-9]{64}$/.test(race.documentSha256)||women&&race.states?.length!==6||!women&&race.states!==undefined)throw new Error('RACE_CONTRACT');ids.add(race.raceId);prev=race.date;
  for(let i=0;i<6;i++){const row=race.results[i],state=resultState(race,i);if(!['classified','not_listed','DNS'].includes(state))throw new Error('RESULT_STATE');if(row===null){if(state==='classified')throw new Error('RESULT_STATE');continue}if(state!=='classified'||!Array.isArray(row)||row.length!==3||!Number.isInteger(row[0])||row[0]<1||!Number.isInteger(row[1])||row[1]<0||row[1]>90||typeof row[2]!=='string')throw new Error('RESULT_CONTRACT');const bouts=row[2].split('+');if(bouts.length!==race.shootings||bouts.some(v=>!/^[0-5]$/.test(v)))throw new Error('SHOOTING_CONTRACT');}
 }
 for(let i=0;i<6;i++)if(data.races.reduce((n,r)=>n+(r.results[i]?.[1]??0),0)!==data.athletes[i].finalPoints)throw new Error('FINAL_TOTAL_MISMATCH');return true;
}
export function sourceUrl(id){if(!/^BT2526SWRLCP0[1-9]S[MW](IN|SI|SP|PU|MS)$/.test(id))throw new Error('RACE_URL_ID');return 'https://biathlonresults.com/modules/sportapi/api/Results?RaceId='+id}
export function phaseRaces(data,phase='all'){if(!Object.hasOwn(phaseLabel,phase))throw new Error('PHASE');return data.races.filter(r=>phase==='all'||phase==='december'&&r.date.startsWith('2025-12')||phase==='january'&&r.date.startsWith('2026-01')||phase==='march'&&r.date.startsWith('2026-03'))}
export function athleteStats(data,key,phase='all'){
 const i=data.athletes.findIndex(a=>a.key===key);if(i<0)throw new Error('ATHLETE');const races=phaseRaces(data,phase),rows=races.map(r=>r.results[i]).filter(r=>r!==null),ranked=rows.map(r=>r[0]).sort((a,b)=>a-b);const finishes=rows.length,points=rows.reduce((n,r)=>n+r[1],0),podiumPoints=rows.filter(r=>r[0]<=3).reduce((n,r)=>n+r[1],0);
 return {key,points,finishes,notListed:races.filter(r=>resultState(r,i)==='not_listed').length,dns:races.filter(r=>resultState(r,i)==='DNS').length,wins:rows.filter(r=>r[0]===1).length,podiums:rows.filter(r=>r[0]<=3).length,top5:rows.filter(r=>r[0]<=5).length,top10:rows.filter(r=>r[0]<=10).length,podiumPoints,otherPoints:points-podiumPoints,medianRank:finishes?(ranked[Math.floor((finishes-1)/2)]+ranked[Math.floor(finishes/2)])/2:null,meanPoints:finishes?points/finishes:null};
}
export function comparison(data,left,right){const li=data.athletes.findIndex(a=>a.key===left),ri=data.athletes.findIndex(a=>a.key===right);if(li<0||ri<0)throw new Error('ATHLETE');let a=0,b=0;return data.races.map((r,i)=>{const l=r.results[li],rr=r.results[ri];a+=l?.[1]??0;b+=rr?.[1]??0;return {index:i+1,raceId:r.raceId,date:r.date,venue:r.venue,discipline:r.discipline,left:l,right:rr,leftState:resultState(r,li),rightState:resultState(r,ri),leftTotal:a,rightTotal:b,gap:a-b};})}
export function commonWindow(data,left,right){const rows=comparison(data,left,right),common=rows.filter(r=>r.left&&r.right);return {races:common.length,leftPoints:common.reduce((n,r)=>n+r.left[1],0),rightPoints:common.reduce((n,r)=>n+r.right[1],0),leftOnlyPoints:rows.filter(r=>r.left&&!r.right).reduce((n,r)=>n+r.left[1],0),rightOnlyPoints:rows.filter(r=>r.right&&!r.left).reduce((n,r)=>n+r.right[1],0)};}
export function shootingStats(data,key){const i=data.athletes.findIndex(a=>a.key===key);if(i<0)throw new Error('ATHLETE');let shots=0,misses=0,races=0;for(const r of data.races){const row=r.results[i];if(!row)continue;races++;shots+=5*r.shootings;misses+=row[2].split('+').map(Number).reduce((a,b)=>a+b,0)}return {races,shots,misses,hits:shots-misses,percentage:shots?100*(shots-misses)/shots:null};}
const cell=value=>{const s=String(value??'');return '"'+(/^[=+\-@\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')+'"'};
export function ledgerCsv(data){validateLedger(data);const rows=[['season','race_id','date','venue','discipline','athlete','ibu_id','state','rank','world_cup_points','misses_per_bout','source_url','source_sha256','fetched_at']];for(const race of data.races)for(let i=0;i<data.athletes.length;i++){const a=data.athletes[i],r=race.results[i],s=resultState(race,i);rows.push([data.season,race.raceId,race.date,race.venue,race.discipline,a.name,a.ibuId,s==='not_listed'?'not_in_result_table':s,r?.[0]??'',r?.[1]??0,r?.[2]??'',sourceUrl(race.raceId),race.documentSha256,race.fetchedAt]);}return '\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')+'\r\n';}
