import {validDate,safeHttpsUrl} from './domain.mjs';
const places={'Kontiolahti':'Контиолахти','Hochfilzen':'Хохфильцен','Ruka':'Рука','Trondheim':'Тронхейм','Le Grand Bornand':'Ле-Гран-Борнан','Davos':'Давос','Pokljuka':'Поклюка','Ruhpolding':'Рупольдинг','Antholz-Anterselva':'Антхольц — Антерсельва','Nove Mesto na Morave':'Нове-Место','Otepää':'Отепя','Oberhof':'Оберхоф','Oestersund':'Эстерсунд','Oslo':'Осло','Les Rousses':'Ле-Русс','Oberstdorf':'Оберстдорф','Val di Fiemme':'Валь-ди-Фьемме','Engadin':'Энгадин','Toblach':'Тоблах / Доббьяко','Lahti':'Лахти','Falun':'Фалун','Drammen':'Драммен','Ulricehamn':'Ульрисехамн'};
const countries={Finland:'Финляндия',Austria:'Австрия',Norway:'Норвегия',France:'Франция',Switzerland:'Швейцария',Slovenia:'Словения',Germany:'Германия',Italy:'Италия',Czechia:'Чехия',Estonia:'Эстония',Sweden:'Швеция',Russia:'Россия'};
export function stagePlace(c){return places[c.location]||c.location||'Место уточняется'}
export function stageCountry(c){return countries[c.country]||c.country||''}
export function stageSeries(value){return ({'IBU World Cup':'Кубок мира · IBU','FIS World Cup':'Кубок мира · FIS','IBU World Championships':'Чемпионат мира · IBU','FIS Nordic World Ski Championships':'Чемпионат мира · FIS'})[value]||value}
export function stageStatus(value){return ({scheduled:'В календаре',provisional:'Проект календаря',tentative:'Предварительно',cancelled:'Отменён',completed:'Завершён',postponed:'Перенесён'})[value]||'Статус уточняется'}
export function stageDateRange(from,to){if(!validDate(from)||!validDate(to)||from>to)return 'Даты уточняются';const options={day:'numeric',month:'short',year:'numeric',timeZone:'UTC'};const f=new Intl.DateTimeFormat('ru-RU',options);return from===to?f.format(new Date(from+'T12:00:00Z')):f.formatRange(new Date(from+'T12:00:00Z'),new Date(to+'T12:00:00Z'))}
export function normalizeStageFilters(params={}){const pick=(k,a)=>typeof params[k]==='string'&&a.includes(params[k])?params[k]:'';return {sport:pick('sport',['biathlon','cross_country']),scope:pick('scope',['russia','international']),month:pick('month',['2026-10','2026-11','2026-12','2027-01','2027-02','2027-03','2027-04','2027-05']),status:pick('status',['scheduled','provisional','tentative','cancelled','completed']),programme:pick('programme',['available','pending']),q:typeof params.q==='string'?params.q.replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,80):''}}
const fold=x=>String(x??'').normalize('NFKC').toLocaleLowerCase('ru-RU').replaceAll('ё','е');
export function catalogueModels(competitions,races){
 const ids=new Set();for(const c of competitions){if(ids.has(c.id))throw new Error('DUPLICATE_STAGE_ID');ids.add(c.id)}
 const groups=new Map();for(const race of races||[]){if(!groups.has(race.competition_id))groups.set(race.competition_id,[]);groups.get(race.competition_id).push(race)}
 return competitions.map(c=>{const linked=groups.get(c.id)||[];const rows=linked.filter(r=>r.sport===c.sport&&r.scope===c.scope&&validDate(r.event_date)&&r.event_date>=c.start_date&&r.event_date<=c.end_date&&safeHttpsUrl(r.source_url)&&r.verified_at).sort((a,b)=>a.event_date.localeCompare(b.event_date)||(a.start_time_msk||'99').localeCompare(b.start_time_msk||'99')||a.id-b.id);
 const summary=races===null?null:{total:rows.length,active:rows.filter(r=>r.status!=='cancelled').length,cancelled:rows.filter(r=>r.status==='cancelled').length,timed:rows.filter(r=>!!r.start_time_msk).length,excluded:linked.length-rows.length};return {competition:c,races:rows,summary};});
}
export function filterStageModels(models,filters){const tokens=fold(filters.q).split(/\s+/).filter(Boolean);return models.filter(({competition:c,summary})=>{
 if(filters.sport&&c.sport!==filters.sport||filters.scope&&c.scope!==filters.scope||filters.status&&c.status!==filters.status)return false;
 if(filters.month){const first=filters.month+'-01',last=new Date(Date.UTC(Number(filters.month.slice(0,4)),Number(filters.month.slice(5,7)),0)).toISOString().slice(0,10);if(c.start_date>last||c.end_date<first)return false;}
 if(filters.programme==='available'&&(!summary||summary.total===0)||filters.programme==='pending'&&(!summary||summary.total!==0))return false;
 const text=fold([c.name,c.series,stageSeries(c.series),c.location,stagePlace(c),c.country,stageCountry(c)].join(' '));return tokens.every(t=>text.includes(t));});}
export function groupProgramme(races){const groups=new Map();for(const r of races){if(!validDate(r.event_date))continue;if(!groups.has(r.event_date))groups.set(r.event_date,[]);groups.get(r.event_date).push(r)}return [...groups].sort(([a],[b])=>a.localeCompare(b)).map(([date,rows])=>({date,races:rows}));}
export function programmeSources(races){return [...new Set(races.map(r=>safeHttpsUrl(r.source_url)).filter(Boolean))]}
