import {assertNoSecrets,validateRef} from './contracts.mjs';

const SOURCE_KINDS=new Set(['official','organizer','secondary','community','social']);
const CONFIDENCE=new Set(['unknown','low','medium','high','verified']);
const FACT_DECISIONS=new Set(['pass','block','review_required']);
const CHECK_DECISIONS=new Set(['supported','conflicted','unsupported','stale','not_applicable']);

function obj(value,name){if(value===null||typeof value!=='object'||Array.isArray(value))throw new Error(`${name}_NOT_OBJECT`);assertNoSecrets(value,name.toLowerCase());return value}
function str(value,name,{max=10000,empty=false}={}){if(typeof value!=='string'||(!empty&&!value.trim())||value.length>max)throw new Error(`${name}_INVALID`);return value}
function arr(value,name,{max=500}={}){if(!Array.isArray(value)||value.length>max)throw new Error(`${name}_INVALID`);return value}
function iso(value,name){str(value,name,{max:64});if(Number.isNaN(Date.parse(value)))throw new Error(`${name}_INVALID`);return value}
function refs(value,name){arr(value,name,{max:100});if(value.some(x=>!validateRef(x)))throw new Error(`${name}_INVALID`);return value}
function bool(value,name){if(typeof value!=='boolean')throw new Error(`${name}_INVALID`);return value}
function confidence(value,name='CONFIDENCE'){if(!CONFIDENCE.has(value))throw new Error(`${name}_INVALID`);return value}
function sourceKind(value){if(!SOURCE_KINDS.has(value))throw new Error('SOURCE_KIND_INVALID');return value}

export function sourceAuthority(kind){sourceKind(kind);return {official:5,organizer:4,secondary:3,community:2,social:1}[kind]}
export function compareSourceAuthority(a,b){return sourceAuthority(b.kind)-sourceAuthority(a.kind)}

export function validateSourceSnapshot(v){obj(v,'SOURCE_SNAPSHOT');str(v.snapshotId,'SNAPSHOT_ID',{max:200});sourceKind(v.kind);str(v.sourceUrl,'SOURCE_URL',{max:2048});if(!validateRef(v.sourceUrl)||!v.sourceUrl.startsWith('https://'))throw new Error('SOURCE_URL_INVALID');iso(v.fetchedAt,'FETCHED_AT');str(v.sha256,'SHA256',{max:64});if(!/^[a-f0-9]{64}$/i.test(v.sha256))throw new Error('SHA256_INVALID');bool(v.official,'OFFICIAL');if(v.official&&!['official','organizer'].includes(v.kind))throw new Error('OFFICIAL_FLAG_KIND_MISMATCH');return v}
export function validateCandidateEvent(v){obj(v,'CANDIDATE_EVENT');str(v.eventId,'EVENT_ID',{max:200});str(v.topic,'TOPIC',{max:300});refs(v.sourceRefs,'SOURCE_REFS');confidence(v.confidence);bool(v.requiresReview,'REQUIRES_REVIEW');return v}
export function validateMediaCandidate(v){obj(v,'MEDIA_CANDIDATE');str(v.mediaId,'MEDIA_ID',{max:200});str(v.athleteRef,'ATHLETE_REF',{max:300});str(v.sourceUrl,'SOURCE_URL',{max:2048});if(!validateRef(v.sourceUrl))throw new Error('SOURCE_URL_INVALID');str(v.license,'LICENSE',{max:200});if(!Number.isInteger(v.width)||v.width<1||!Number.isInteger(v.height)||v.height<1)throw new Error('MEDIA_DIMENSIONS_INVALID');bool(v.identityReviewed,'IDENTITY_REVIEWED');bool(v.rightsReviewed,'RIGHTS_REVIEWED');if(v.identityReviewed||v.rightsReviewed)throw new Error('SCOUT_CANNOT_PREAPPROVE_MEDIA');return v}
export function validateCuratedMediaCandidate(v){obj(v,'CURATED_MEDIA');str(v.mediaId,'MEDIA_ID',{max:200});str(v.athleteRef,'ATHLETE_REF',{max:300});confidence(v.confidence);bool(v.identityReviewed,'IDENTITY_REVIEWED');bool(v.rightsReviewed,'RIGHTS_REVIEWED');bool(v.deployable,'DEPLOYABLE');if(v.deployable)throw new Error('CURATOR_CANNOT_SET_DEPLOYABLE');refs(v.sourceRefs,'SOURCE_REFS');return v}
export function validateVerifiedMedia(v){obj(v,'VERIFIED_MEDIA');str(v.mediaId,'MEDIA_ID',{max:200});str(v.athleteRef,'ATHLETE_REF',{max:300});bool(v.identityReviewed,'IDENTITY_REVIEWED');bool(v.rightsReviewed,'RIGHTS_REVIEWED');if(!v.identityReviewed||!v.rightsReviewed)throw new Error('VERIFIED_MEDIA_WITHOUT_APPROVALS');arr(v.approvals,'MEDIA_APPROVALS',{max:20});for(const gate of ['identity-reviewed','rights-reviewed'])if(!v.approvals.includes(gate))throw new Error(`VERIFIED_MEDIA_GATE_MISSING:${gate}`);refs(v.sourceRefs,'SOURCE_REFS');str(v.credit,'MEDIA_CREDIT',{max:1000});return v}
export function validateManualReview(v){obj(v,'MANUAL_REVIEW');str(v.reviewId,'REVIEW_ID',{max:200});str(v.reason,'REASON',{max:1000});str(v.subjectRef,'SUBJECT_REF',{max:2048});confidence(v.confidence);return v}

function validateEvidenceSource(s){obj(s,'EVIDENCE_SOURCE');str(s.sourceId,'SOURCE_ID',{max:200});sourceKind(s.kind);str(s.url,'SOURCE_URL',{max:2048});if(!validateRef(s.url)||!s.url.startsWith('https://'))throw new Error('SOURCE_URL_INVALID');if(s.publishedAt!==null&&s.publishedAt!==undefined)iso(s.publishedAt,'PUBLISHED_AT');iso(s.observedAt,'OBSERVED_AT');return s}
function validateClaim(c,sourceIds){obj(c,'CLAIM');str(c.claimId,'CLAIM_ID',{max:200});str(c.text,'CLAIM_TEXT',{max:4000});if(!['fact','analysis','uncertainty'].includes(c.kind))throw new Error('CLAIM_KIND_INVALID');confidence(c.confidence);arr(c.sourceIds,'CLAIM_SOURCE_IDS',{max:30});if(c.sourceIds.length===0||c.sourceIds.some(id=>!sourceIds.has(id)))throw new Error('CLAIM_SOURCE_IDS_INVALID');bool(c.mutable,'CLAIM_MUTABLE');return c}
export function validateEvidencePacket(v){obj(v,'EVIDENCE_PACKET');str(v.packetId,'PACKET_ID',{max:200});str(v.topic,'TOPIC',{max:500});iso(v.createdAt,'CREATED_AT');arr(v.sources,'SOURCES',{max:100});const ids=new Set();for(const s of v.sources){validateEvidenceSource(s);if(ids.has(s.sourceId))throw new Error('SOURCE_ID_DUPLICATE');ids.add(s.sourceId)}arr(v.claims,'CLAIMS',{max:200});const claimIds=new Set();for(const c of v.claims){validateClaim(c,ids);if(claimIds.has(c.claimId))throw new Error('CLAIM_ID_DUPLICATE');claimIds.add(c.claimId)}arr(v.conflicts,'CONFLICTS',{max:100});for(const conflict of v.conflicts){obj(conflict,'CONFLICT');str(conflict.claimId,'CONFLICT_CLAIM_ID',{max:200});if(!claimIds.has(conflict.claimId))throw new Error('CONFLICT_CLAIM_UNKNOWN');str(conflict.note,'CONFLICT_NOTE',{max:2000})}return v}
export function validateFactCheckReport(v){obj(v,'FACT_CHECK_REPORT');str(v.reportId,'REPORT_ID',{max:200});str(v.packetId,'PACKET_ID',{max:200});if(!FACT_DECISIONS.has(v.decision))throw new Error('FACT_DECISION_INVALID');arr(v.checks,'FACT_CHECKS',{max:200});for(const c of v.checks){obj(c,'FACT_CHECK');str(c.claimId,'CLAIM_ID',{max:200});if(!CHECK_DECISIONS.has(c.decision))throw new Error('CLAIM_CHECK_DECISION_INVALID');refs(c.sourceRefs,'SOURCE_REFS');str(c.note??'','CHECK_NOTE',{max:2000,empty:true})}if(v.decision==='pass'&&v.checks.some(c=>['conflicted','unsupported','stale'].includes(c.decision)))throw new Error('FACT_PASS_WITH_BLOCKING_CHECK');return v}
export function validateApprovedEvidence(v){obj(v,'APPROVED_EVIDENCE');validateEvidencePacket(v.packet);validateFactCheckReport(v.report);if(v.report.packetId!==v.packet.packetId)throw new Error('EVIDENCE_REPORT_PACKET_MISMATCH');if(v.report.decision!=='pass')throw new Error('EVIDENCE_NOT_APPROVED');return v}
export function validateArticleDraft(v){obj(v,'ARTICLE_DRAFT');str(v.draftId,'DRAFT_ID',{max:200});str(v.title,'TITLE',{max:240});str(v.dek,'DEK',{max:600});str(v.body,'BODY',{max:120000});arr(v.claimIds,'CLAIM_IDS',{max:200});refs(v.sourceRefs,'SOURCE_REFS');obj(v.seo,'SEO');str(v.seo.title,'SEO_TITLE',{max:240});str(v.seo.description,'SEO_DESCRIPTION',{max:600});arr(v.internalLinks,'INTERNAL_LINKS',{max:100});for(const link of v.internalLinks)if(!validateRef(link))throw new Error('INTERNAL_LINK_INVALID');return v}
export function validateVisualPackage(v){obj(v,'VISUAL_PACKAGE');str(v.packageId,'PACKAGE_ID',{max:200});str(v.draftId,'DRAFT_ID',{max:200});bool(v.namedPersonMedia,'NAMED_PERSON_MEDIA');arr(v.media,'MEDIA',{max:50});for(const m of v.media){obj(m,'VISUAL_MEDIA');str(m.mediaRef,'MEDIA_REF',{max:2048});bool(m.identityReviewed,'IDENTITY_REVIEWED');bool(m.rightsReviewed,'RIGHTS_REVIEWED');str(m.credit,'MEDIA_CREDIT',{max:1000});if(v.namedPersonMedia&&(!m.identityReviewed||!m.rightsReviewed))throw new Error('VISUAL_NAMED_PERSON_MEDIA_UNREVIEWED')}return v}
export function validateQaReport(v){obj(v,'QA_REPORT');str(v.reportId,'REPORT_ID',{max:200});bool(v.passed,'QA_PASSED');arr(v.checks,'QA_CHECKS',{max:200});for(const c of v.checks){obj(c,'QA_CHECK');str(c.name,'QA_CHECK_NAME',{max:200});if(!['pass','fail','warning'].includes(c.status))throw new Error('QA_CHECK_STATUS_INVALID');str(c.note??'','QA_CHECK_NOTE',{max:2000,empty:true})}if(v.passed&&v.checks.some(c=>c.status==='fail'))throw new Error('QA_PASS_WITH_FAILED_CHECK');return v}
export function validateReleaseCandidate(v){obj(v,'RELEASE_CANDIDATE');str(v.releaseId,'RELEASE_ID',{max:200});str(v.revision,'REVISION',{max:200});refs(v.artifactRefs,'ARTIFACT_REFS');arr(v.approvals,'APPROVALS',{max:30});for(const gate of ['fact-check-passed','qa-passed'])if(!v.approvals.includes(gate))throw new Error(`RELEASE_GATE_MISSING:${gate}`);return v}
export function validatePublicationRecord(v){obj(v,'PUBLICATION_RECORD');str(v.publicationId,'PUBLICATION_ID',{max:200});str(v.releaseId,'RELEASE_ID',{max:200});str(v.revision,'REVISION',{max:200});iso(v.publishedAt,'PUBLISHED_AT');refs(v.sourceRefs,'SOURCE_REFS');arr(v.approvals,'APPROVALS',{max:30});for(const gate of ['fact-check-passed','qa-passed'])if(!v.approvals.includes(gate))throw new Error(`PUBLICATION_GATE_MISSING:${gate}`);return v}

export const artifactValidators={validateSourceSnapshot,validateCandidateEvent,validateMediaCandidate,validateCuratedMediaCandidate,validateVerifiedMedia,validateManualReview,validateEvidencePacket,validateFactCheckReport,validateApprovedEvidence,validateArticleDraft,validateVisualPackage,validateQaReport,validateReleaseCandidate,validatePublicationRecord};
