import Link from 'next/link';import {notFound} from 'next/navigation';import {CalendarDays,MapPin,ArrowLeft} from 'lucide-react';import {SiteNav} from '../../../components/SiteNav';import {RaceList} from '../../../components/RaceList';import {ArchiveNote} from '../../../components/stages/ArchiveNote';import {SaveButton} from '../../../components/personal/SaveButton';import {ShareButton} from '../../../components/personal/ShareButton';import {getStageCatalogue} from '../../../lib/stage-data';import {groupProgramme,stageCountry,stageDateRange,stagePlace,stageSeries,stageStatus,programmeSources} from '../../../lib/stage-catalog.mjs';import {formatDate,safeHttpsUrl,sportLabel} from '../../../lib/domain.mjs';import {pageMetadata} from '../../../lib/seo';import styles from '../../../components/stages/Stages.module.css';
export const dynamic='force-dynamic';type Props={params:Promise<{id:string}>};
async function modelFor(id:string){if(!/^[1-9]\d{0,14}$/.test(id))return null;const data=await getStageCatalogue();if(data.unavailable)throw new Error('STAGE_CATALOGUE_UNAVAILABLE');return data.models.find(s=>String(s.competition.id)===id)||null}
export async function generateMetadata({params}:Props){const model=await modelFor((await params).id);return model?pageMetadata(`${model.competition.name}: программа, ${stagePlace(model.competition)}`,`${sportLabel(model.competition.sport)}. Даты этапа, отдельные гонки и подтверждённые источники.`,`/competitions/${model.competition.id}`):{title:'Этап не найден',robots:{index:false}}}
export default async function CompetitionPage({params}:Props){
 const model=await modelFor((await params).id);if(!model)notFound();const {competition:c,summary,races}=model;const days=groupProgramme(races),source=safeHttpsUrl(c.source_url),sources=programmeSources(races);const data=await getStageCatalogue();const siblings=data.models.filter(s=>s.competition.sport===c.sport&&s.competition.scope===c.scope);const index=siblings.findIndex(s=>s.competition.id===c.id);const previous=siblings[index-1]?.competition,next=siblings[index+1]?.competition;
 return <main id="main-content" className={styles.shell}><SiteNav/><Link className={styles.back} href={`/competitions?sport=${c.sport}&scope=${c.scope}`}><ArrowLeft size={14} aria-hidden="true"/> К этапам этого направления</Link>
  <header className={styles.detailHero}><div className={styles.seasonLabel}>{sportLabel(c.sport)} · {stageSeries(c.series)} · 2026/27</div><h1>{c.name}</h1><p>{stagePlace(c)} · {stageCountry(c)}</p><div className={styles.detailFacts}><span><CalendarDays size={17} aria-hidden="true"/>{stageDateRange(c.start_date,c.end_date)}</span><span><MapPin size={16} aria-hidden="true"/>{c.scope==='russia'?'Россия':'Международные'}</span><span className={styles.tag}>{stageStatus(c.status)}</span></div><div className="entityTools"><SaveButton kind="stage" id={c.id} label={stagePlace(c)}/><ShareButton kind="stage" id={c.id} title={`${stagePlace(c)} — ${stageSeries(c.series)}`}/></div></header>
  {['provisional','tentative'].includes(c.status)&&<div className={styles.problem}>Опубликован проект календаря. Даты и форматы могут измениться; авторитет федерации не превращает проект в окончательный регламент.</div>}{c.status==='cancelled'&&<div className={styles.problem}>В базе этот этап отмечен как отменённый. Записи сохранены для истории; проверяйте обновления первоисточника.</div>}
  <div className={styles.programmeLayout}><section><h2>Программа гонок</h2>{summary&&<div className={styles.detailStats}><span><b>{summary.total}</b> записей</span><span><b>{summary.active}</b> не отменено</span><span><b>{summary.cancelled}</b> отменено</span><span><b>{summary.timed}</b> с точным временем</span></div>}{days.length>0&&<nav aria-label="Дни программы" className={styles.dayNav}>{days.map(d=><a href={'#day-'+d.date} key={d.date}>{d.date.slice(8,10)}.{d.date.slice(5,7)}</a>)}</nav>}{summary&&summary.excluded>0&&<div className={styles.problem}>Некоторые связи не соответствуют этапу. Спорные записи не включены в программу.</div>}
   {!summary?<RaceList races={[]} unavailable/>:days.length?days.map(d=><section className={styles.day} id={'day-'+d.date} key={d.date}><h3>{formatDate(d.date)}</h3><RaceList races={d.races}/></section>):<><div className="emptyState"><h2>Подробная программа ещё не внесена</h2><p>Даты этапа известны, но отдельных гонок в опубликованной базе пока нет.</p>{source&&<a href={source} target="_blank" rel="noopener noreferrer">Проверить программу организатора ↗</a>}</div><p className={styles.countNote}>Дни приезда, тренировок и отъезда не превращаются в гонки автоматически.</p></>}
  </section><aside><section className={styles.sidePanel}><h2>Первоисточники</h2>{source&&<a href={source} target="_blank" rel="noopener noreferrer">Официальный источник ↗</a>}{sources.filter(u=>u!==source).slice(0,5).map((u,i)=><div key={u}><a href={u} target="_blank" rel="noopener noreferrer">Программа отдельных гонок{sources.length>1?` · ${i+1}`:''} ↗</a></div>)}<p>Проверка этапа в базе: {c.verified_at?new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',dateStyle:'medium',timeStyle:'short'}).format(new Date(c.verified_at))+' МСК':'не указана'}.</p><p>Время проверки этапа не означает, что все его гонки проверены одновременно.</p>{c.notes&&<details><summary>Примечание редактора</summary><p>{c.notes}</p></details>}<Link href="/methodology">Методология →</Link></section>
   <section className={styles.sidePanel}><h2>Сохранить программу</h2><Link href="/my-season">Мои этапы и гонки →</Link>{summary&&summary.total>0?<a href={`/api/calendar.ics?competition=${c.id}`}>Скачать гонки этапа в ICS →</a>:<p>Экспорт появится с опубликованными гонками.</p>}<p>Если точного времени нет, календарь получает отметку даты на весь день — без выдуманного часа старта.</p><Link href="/calendar/subscribe">Подписка на сезон →</Link></section><section className={styles.sidePanel}><h2>Где смотреть</h2><p>Проверенные эфиры указываются в отдельных карточках гонок. Наличие этапа не подтверждает ни вещателя, ни регион доступности.</p><Link href="/guides/translyaciya-i-vremya-starta">Как проверить трансляцию →</Link></section>
  </aside></div><ArchiveNote competitionKey={c.external_key}/>{(previous||next)&&<nav className={styles.adjacent} aria-label="Рядом в календаре">{previous&&<Link href={`/competitions/${previous.id}`}><small>РАНЕЕ В КАЛЕНДАРЕ</small>{stagePlace(previous)} · {previous.name}</Link>}{next&&<Link href={`/competitions/${next.id}`}><small>ДАЛЕЕ В КАЛЕНДАРЕ</small>{stagePlace(next)} · {next.name}</Link>}</nav>}
 </main>;
}
