import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteNav} from '../../../components/SiteNav';
import {RaceList} from '../../../components/RaceList';
import {getCompetition,getRaces} from '../../../lib/data';
import {competitionMatches} from '../../../lib/calendar-window.mjs';
import {formatDate,raceStatus,safeHttpsUrl,sportLabel} from '../../../lib/domain.mjs';
import {pageMetadata} from '../../../lib/seo';
export const dynamic='force-dynamic';type Props={params:Promise<{id:string}>};
export async function generateMetadata({params}:Props){const c=await getCompetition((await params).id);return c?pageMetadata(`${c.name}: программа и расписание`,`${sportLabel(c.sport)}. ${c.location||'Место уточняется'}. Даты этапа и опубликованные гонки.`,`/competitions/${c.id}`):{title:'Этап не найден',robots:{index:false}}}
export default async function CompetitionPage({params}:Props){const c=await getCompetition((await params).id);if(!c)notFound();const result=await getRaces({competitionId:c.id,from:c.start_date,to:c.end_date});const races=result.races.filter(r=>competitionMatches(r,c));const conflict=races.length!==result.races.length;const source=safeHttpsUrl(c.source_url);return <main id="main-content"><SiteNav/><header className="calendarHeader"><div className="eyebrow">{sportLabel(c.sport)} · {c.scope==='russia'?'РОССИЯ':'МИР'}</div><h1 className="detailTitle">{c.name}</h1><p className="lead">{c.series} · {c.location||'Место уточняется'}{c.country?' · '+c.country:''}</p><div className="detailFacts"><span>{formatDate(c.start_date)} — {formatDate(c.end_date)}</span><span className={'status '+c.status}>{raceStatus(c.status)}</span></div></header>{c.status==='provisional'&&<div className="notice">Организатор опубликовал проект календаря. Эти даты и форматы могут измениться.</div>}<div className="grid"><section><h2>Программа гонок</h2>{conflict&&<div className="notice">Часть связей требует проверки. Спорные записи не показаны в программе этапа.</div>}<RaceList races={races} unavailable={result.unavailable}/>{!races.length&&!result.unavailable&&<p className="metricNote">Этап опубликован, но подробные гонки ещё не внесены. Дни приезда, тренировок и отъезда не превращаются в гонки автоматически.</p>}</section><aside><article className="panel"><small>ПЕРВОИСТОЧНИК</small><h2>Программа организатора</h2>{source&&<a className="watchButton" href={source} target="_blank" rel="noopener noreferrer">Официальный источник ↗</a>}<p>Проверка в базе: {c.verified_at?new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',dateStyle:'medium',timeStyle:'short'}).format(new Date(c.verified_at))+' МСК':'не указана'}.</p>{c.notes&&<p>{c.notes}</p>}<Link href="/methodology">Как проверяем →</Link></article><article className="panel"><Link href={`/calendar?sport=${c.sport}&scope=${c.scope}`}>Календарь этого направления →</Link></article></aside></div></main>}
