import Link from 'next/link';import {articleTypeLabel,athleteLabel} from '../../lib/editorial';import {MAX_QUERY_LENGTH,searchSortLabels,type DiscoveryOptions} from '../../lib/editorial-discovery.mjs';import styles from './ArticleFilters.module.css';
export function ArticleFilters({values}:{values:DiscoveryOptions}){
 return <form key={JSON.stringify([values.query,values.sport,values.type,values.athlete,values.sort])} className={styles.form} action="/media" method="get" aria-label="Фильтры материалов">
  <div className={styles.search}><label htmlFor="article-query">Поиск по материалам</label><input id="article-query" type="search" name="q" defaultValue={values.query} maxLength={MAX_QUERY_LENGTH} placeholder="Фамилия, тема, Tour de Ski…" aria-describedby="article-search-help" aria-invalid={!!values.queryError}/><p id="article-search-help">По заголовкам и полным проверенным текстам. Клебо, Клэбо и Klaebo — одна поисковая фамилия.</p></div>
  <div className={styles.field}><label htmlFor="article-sport">Вид спорта</label><select id="article-sport" name="sport" defaultValue={values.sport||''}><option value="">Все виды</option><option value="biathlon">Биатлон</option><option value="cross_country">Лыжные гонки</option></select></div>
  <div className={styles.field}><label htmlFor="article-type">Формат</label><select id="article-type" name="type" defaultValue={values.type}><option value="">Все материалы</option>{Object.entries(articleTypeLabel).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>
  <div className={styles.field}><label htmlFor="article-athlete">Спортсмен</label><select id="article-athlete" name="athlete" defaultValue={values.athlete}><option value="">Все спортсмены</option>{Object.entries(athleteLabel).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>
  <div className={styles.field}><label htmlFor="article-sort">Порядок</label><select id="article-sort" name="sort" defaultValue={values.sort}>{Object.entries(searchSortLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>
  <button type="submit">Найти материалы</button><Link href="/media">Сбросить</Link>
 </form>;
}
