'use client';
import {useId,useState} from 'react';import Link from 'next/link';import {athleteStats,comparison,commonWindow,shootingStats,categoryOf,phaseLabel,sourceUrl,venueLabel,disciplineLabel,type Ledger} from '../../lib/season-ledger.mjs';import styles from './SeasonComparison.module.css';
const signed=(n:number)=>n>0?'+'+n:String(n),short=(s:string)=>s.slice(8,10)+'.'+s.slice(5,7);
function ResultCell({value,state}:{value:(number|string)[]|null;state:string}){return <td>{value?<>{value[0]} / <b>{value[1]}</b><small>{value[2]}</small></>:state==='DNS'?<span>Не стартовала (DNS)</span>:<span>Нет записи</span>}</td>}
export function ComparisonView({data,initialLeft,initialRight,interactive=false}:{data:Ledger;initialLeft:string;initialRight:string;interactive?:boolean}){
 const [left,setLeft]=useState(initialLeft),[right,setRight]=useState(initialRight),prefix=useId();const women=categoryOf(data)==='SW',rows=comparison(data,left,right),ls=athleteStats(data,left),rs=athleteStats(data,right),la=data.athletes.find(a=>a.key===left)!,ra=data.athletes.find(a=>a.key===right)!,common=commonWindow(data,left,right),lh=shootingStats(data,left),rh=shootingStats(data,right);
 const lp=[0,...rows.map(r=>r.leftTotal)],rp=[0,...rows.map(r=>r.rightTotal)],maximum=Math.max(200,Math.ceil(Math.max(...lp,...rp)/200)*200),x=(i:number)=>48+i*28,y=(n:number)=>270-220*n/maximum,poly=(p:number[])=>p.map((v,i)=>`${x(i)},${y(v)}`).join(' '),final=rows.at(-1)!;
 const csv=women?'/api/editorial/women-season-2526.csv':'/api/editorial/season-2526.csv',lab=women?'/media/season-2025-26/women':'/media/season-2025-26';
 return <section className={styles.panel} aria-label="Сравнение полного сезона" data-season-comparison data-category={women?'women':'men'}><div className={styles.title}><b>21 личная гонка · Кубок мира 2025/26</b><span>{women?'Женщины':'Мужчины'} · накопленные очки, без Олимпиады и эстафет</span></div>
 {interactive&&<div className={styles.controls}><div><label htmlFor={prefix+'-left'}>{women?'Первая спортсменка':'Первый спортсмен'}</label><select id={prefix+'-left'} value={left} onChange={e=>setLeft(e.target.value)}>{data.athletes.map(a=><option value={a.key} key={a.key}>{a.name}</option>)}</select></div><div><label htmlFor={prefix+'-right'}>{women?'Вторая спортсменка':'Второй спортсмен'}</label><select id={prefix+'-right'} value={right} onChange={e=>setRight(e.target.value)}>{data.athletes.map(a=><option value={a.key} key={a.key}>{a.name}</option>)}</select></div></div>}
 <div className={styles.legend}><span className={styles.first}>{la.name}: <b>{ls.points}</b></span><span className={styles.second}>{ra.name}: <b>{rs.points}</b></span></div>
 <svg className={styles.chart} viewBox="0 0 680 314" role="img" aria-labelledby={prefix+'-title '+prefix+'-desc'}><title id={prefix+'-title'}>{`Накопление очков: ${la.name} и ${ra.name}`}</title><desc id={prefix+'-desc'}>{`21 гонка по порядку, не равные интервалы дней. Итог ${ls.points}:${rs.points}. Полная таблица ниже. Отсутствие записи не равно нулевому месту.`}</desc>{[0,1,2,3,4].map(k=>{const n=maximum*k/4;return <g key={k}><line x1="48" x2="646" y1={y(n)} y2={y(n)} className={styles.gridLine}/><text x="39" y={y(n)+4} textAnchor="end" className={styles.axis}>{n}</text></g>})}<polyline points={poly(lp)} className={styles.lineLeft}/><polyline points={poly(rp)} className={styles.lineRight}/>{rows.map(r=><g key={r.raceId}><circle cx={x(r.index)} cy={y(r.leftTotal)} r="3" className={styles.dotLeft}><title>{`${short(r.date)} ${la.name}: ${r.leftTotal}; ${r.left?'место '+r.left[0]:r.leftState==='DNS'?'официальный DNS':'нет записи'}`}</title></circle><rect x={x(r.index)-3} y={y(r.rightTotal)-3} width="6" height="6" className={styles.dotRight}><title>{`${short(r.date)} ${ra.name}: ${r.rightTotal}; ${r.right?'место '+r.right[0]:r.rightState==='DNS'?'официальный DNS':'нет записи'}`}</title></rect></g>)}{[1,8,14,21].map(i=><text key={i} x={x(i)} y="296" textAnchor="middle" className={styles.axis}>{short(rows[i-1].date)}</text>)}</svg>
 <p className={styles.note}>По горизонтали — порядок гонок, не равные интервалы дней. Промежуточный счёт реконструирован из финальных протоколов, не из архива рейтингов каждого дня. Отсутствие результата не обнуляет накопленную сумму.</p>
 <div className={styles.tableWrap} role="region" aria-label="Сводка сравнения" tabIndex={0}><table><caption>Результаты полного зачётного сезона</caption><thead><tr><th>Показатель</th><th>{la.name}</th><th>{ra.name}</th></tr></thead><tbody>{[['Финиши',ls.finishes,rs.finishes],['Победы',ls.wins,rs.wins],['Подиумы',ls.podiums,rs.podiums],['Топ-5',ls.top5,rs.top5],['Очки на подиумах',ls.podiumPoints,rs.podiumPoints],['Остальные очки',ls.otherPoints,rs.otherPoints],['Нет записи в протоколе',ls.notListed,rs.notListed],...(women?[['Официальный DNS',ls.dns,rs.dns]]:[])].map(([label,l,r])=><tr key={label}><th scope="row">{label}</th><td>{l}</td><td>{r}</td></tr>)}</tbody></table></div>
 <div className={styles.tableWrap} role="region" aria-label="Очки по частям сезона" tabIndex={0}><table><caption>Календарные блоки, не диагностика формы</caption><thead><tr><th>Период</th><th>{la.name}</th><th>{ra.name}</th><th>Разница за блок</th></tr></thead><tbody>{['december','january','march'].map(p=>{const l=athleteStats(data,left,p),r=athleteStats(data,right,p);return <tr key={p}><th scope="row">{phaseLabel[p]}</th><td>{l.points}</td><td>{r.points}</td><td>{signed(l.points-r.points)}</td></tr>})}</tbody></table></div>
 <p className={styles.note} role="status">Итоговая разница (первый − второй): {signed(final.gap)} очков.</p>
 <details className={styles.details} data-common-window><summary>Сравнить только совпадающие финиши</summary><div className={styles.tableWrap} role="region" aria-label="Общие финиши" tabIndex={0}><table><caption>{common.races} гонок с классифицированным результатом обоих участников</caption><thead><tr><th>Начисления</th><th>{la.name}</th><th>{ra.name}</th></tr></thead><tbody><tr><th scope="row">На общих финишах</th><td>{common.leftPoints}</td><td>{common.rightPoints}</td></tr><tr><th scope="row">Вне общего набора</th><td>{common.leftOnlyPoints}</td><td>{common.rightOnlyPoints}</td></tr></tbody></table></div><p className={styles.note}>Это описательная подвыборка, не альтернативный зачёт и не прогноз пропущенных гонок. Участие не случайно: фильтр не устраняет различия формы и условий. Очки сохраняются из полного официального поля, а не пересчитываются между двумя фамилиями.</p></details>
 <details className={styles.details} data-shooting-window><summary>Проверить точность и её знаменатель</summary><div className={styles.tableWrap} role="region" aria-label="Стрельба в Кубке мира" tabIndex={0}><table><caption>Только классифицированные личные финиши данного Кубка мира</caption><thead><tr><th>Показатель</th><th>{la.name}</th><th>{ra.name}</th></tr></thead><tbody><tr><th>Гонок</th><td>{lh.races}</td><td>{rh.races}</td></tr><tr><th>Попаданий / выстрелов</th><td>{lh.hits}/{lh.shots}</td><td>{rh.hits}/{rh.shots}</td></tr><tr><th>Точность</th><td>{lh.percentage?.toFixed(1).replace('.',',')}%</td><td>{rh.percentage?.toFixed(1).replace('.',',')}%</td></tr></tbody></table></div><p className={styles.note}>Сумма попаданий делится на сумму выстрелов, а не усредняются проценты гонок. Олимпиада, эстафеты и DNS исключены. Это не все выстрелы спортсмена за зиму: расхождение с сезонным обзором может возникнуть из-за другой выборки. Причины расхождения без совпадающих исходных данных не устанавливаются.</p></details>
 <details className={styles.details}><summary>Показать места, очки и первоисточники</summary><p className={styles.note}>Ячейка: место / очки / промахи. «Нет записи» не заменяется DNS. Указанный DNS перенесён из официальной строки без выдуманного места и выстрелов.</p><div className={styles.tableWrap} role="region" aria-label="Полная таблица гонок" tabIndex={0}><table data-ledger-table><caption>21 гонка; Δ — накопленная разница выбранной пары</caption><thead><tr><th>Дата и гонка</th><th>{la.name}</th><th>{ra.name}</th><th>Δ</th></tr></thead><tbody>{rows.map(r=><tr key={r.raceId}><th scope="row"><a href={sourceUrl(r.raceId)} target="_blank" rel="noopener noreferrer">{short(r.date)} · {venueLabel[r.venue]||r.venue} ↗</a><small>{disciplineLabel[r.discipline]}</small></th><ResultCell value={r.left} state={r.leftState}/><ResultCell value={r.right} state={r.rightState}/><td>{signed(r.gap)}</td></tr>)}</tbody></table></div></details>
 <div className={styles.links}><a href={csv}>{women?'Скачать CSV: 6 спортсменок × 21 гонка':'Скачать CSV: 6 спортсменов × 21 гонка'}</a>{!interactive&&<Link href={lab}>Сравнить других спортсменов →</Link>}</div><p className={styles.note}>Суммы очков сверены с итоговым зачётом IBU. Эта таблица не измеряет лыжную мощность, состояние здоровья или психологические причины результата.</p></section>;
}
