import data from '../../content/editorial/season-data.json';import styles from './Editorial.module.css';
const source=(id:string)=>'#source-'+id;
export function DataFigure({kind}:{kind:string}){
 if(kind==='standings')return <figure className={styles.figure}><figcaption><b>Общий зачёт 2025/26 · первые шесть мест</b><span>Финальная таблица IBU после 21 зачётной гонки</span></figcaption><ol className={styles.bars}>{data.rows.map(r=><li key={r.ibuId}><div><span>{r.rank}. {r.name}</span><strong>{r.points}</strong></div><div className={styles.track} aria-hidden="true"><span style={{width:`${r.points/data.rows[0].points*100}%`}}/></div></li>)}</ol><p className={styles.figureNote}>{data.note} <a href={source(data.sourceId)}>Источник ↗</a></p></figure>;
 if(kind==='streak')return <figure className={styles.figure}><figcaption><b>Пять личных побед подряд</b><span>Только победная серия марта, не все старты сезона</span></figcaption><ol className={styles.timeline}>{[['08.03','Контиолахти · масс-старт','kontiolahti-mass'],['12.03','Отепя · спринт','otepaa-sprint'],['14.03','Отепя · преследование','otepaa-pursuit'],['20.03','Осло · спринт','oslo-sprint'],['21.03','Осло · преследование','oslo-pursuit']].map(([date,label,id])=><li key={id}><b>{date}</b><a href={source(id)}>{label}</a></li>)}</ol><p className={styles.figureNote}>22 марта: четвёртое место в масс-старте, конец серии. <a href={source('oslo-mass')}>Отчёт финальной гонки ↗</a></p></figure>;
 if(kind==='contrast')return <figure className={styles.figure}><figcaption><b>Две победы Джакомеля — два разных сценария</b><span>Факты из отчётов отдельных гонок, не средние за сезон</span></figcaption><div className={styles.dual}><div><strong>10/10</strong><b>12 декабря · Хохфильцен</b><p>Чистый спринт; Перро уступил 0,4 секунды.</p><a href={source('hochfilzen-sprint')}>Источник ↗</a></div><div><strong>6 промахов</strong><b>10 января · Оберхоф</b><p>Победа в преследовании после чистой заключительной стойки.</p><a href={source('oberhof-pursuit')}>Источник ↗</a></div></div></figure>;
 if(kind==='example')return <figure className={styles.figure}><figcaption><b>Одинаковые 90% — разные гонки</b><span>Учебный пример. Это не результаты реальных спортсменов.</span></figcaption><div className={styles.tableWrap}><table><caption>Попадания из двадцати выстрелов в каждой условной гонке</caption><thead><tr><th>Вариант</th><th>Гонка 1</th><th>Гонка 2</th><th>Всего</th></tr></thead><tbody><tr><th>А</th><td>20/20</td><td>16/20</td><td>36/40 · 90%</td></tr><tr><th>Б</th><td>18/20</td><td>18/20</td><td>36/40 · 90%</td></tr></tbody></table></div><p className={styles.figureNote}>Средняя точность совпала; распределение промахов по гонкам — нет. Число очков из этой таблицы восстановить нельзя.</p></figure>;
 if(kind==='finish')return <figure className={styles.figure}><figcaption><b>Осло · преследование · 21 марта 2026</b><span>Результат опубликованной гонки, не модель и не прогноз</span></figcaption><div className={styles.tableWrap}><table><caption>Два лидера по официальному отчёту IBU</caption><thead><tr><th>Место</th><th>Спортсмен</th><th>Финишная отметка</th><th>Стрельба</th></tr></thead><tbody><tr><td>1</td><th>Легрейд</th><td>30:31,4</td><td>20/20</td></tr><tr><td>2</td><th>Перро</th><td>30:31,4</td><td>20/20</td></tr></tbody></table></div><p className={styles.figureNote}>Порядок определён фотофинишем. В преследовании эта отметка не равна чистому времени каждого спортсмена. <a href={source('oslo-pursuit')}>Отчёт IBU ↗</a></p></figure>;
 if(kind==='programme')return <figure className={styles.figure}><figcaption><b>Контиолахти · программа 26–29 ноября 2026</b><span>Срез для раннего превью на 3 октября. Время МСК не установлено.</span></figcaption><ol className={styles.timeline}>{[['26.11','Мужчины · индивидуальная гонка, 20 км'],['27.11','Женщины · индивидуальная гонка, 15 км'],['28.11','Одиночная смешанная и смешанная эстафеты'],['29.11','Спринты: мужчины 10 км, женщины 7,5 км']].map(([date,label])=><li key={date}><b>{date}</b><span>{label}</span></li>)}</ol><p className={styles.figureNote}>Подтверждённых старт-листов здесь нет; программа может измениться. <a href={source('kontiolahti-programme')}>Организатор ↗</a></p></figure>;
 return null;
}
