'use client';
import {useId,useState} from 'react';import Link from 'next/link';import data from '../../content/editorial/full-season-2526.json';import {athleteStats,comparison,phaseLabel,sourceUrl,venueLabel,disciplineLabel} from '../../lib/season-ledger.mjs';import styles from './SeasonComparison.module.css';
const signed=(n:number)=>n>0?'+'+n:String(n);const short=(s:string)=>s.slice(8,10)+'.'+s.slice(5,7);
export function SeasonComparison({initialLeft='botn',initialRight='laegreid',interactive=false}:{initialLeft?:string;initialRight?:string;interactive?:boolean}){
 const [left,setLeft]=useState(initialLeft),[right,setRight]=useState(initialRight);const prefix=useId();const rows=comparison(data,left,right),ls=athleteStats(data,left),rs=athleteStats(data,right),la=data.athletes.find(a=>a.key===left)!,ra=data.athletes.find(a=>a.key===right)!;
 const pointsLeft=[0,...rows.map(r=>r.leftTotal)],pointsRight=[0,...rows.map(r=>r.rightTotal)];const maximum=Math.ceil(Math.max(...pointsLeft,...pointsRight)/200)*200;const x=(i:number)=>48+i*28,y=(n:number)=>270-220*n/maximum;const poly=(points:number[])=>points.map((v,i)=>`${x(i)},${y(v)}`).join(' ');const final=rows.at(-1)!;
 return <section className={styles.panel} aria-label="Сравнение полного сезона" data-season-comparison><div className={styles.title}><b>21 личная гонка · Кубок мира 2025/26</b><span>Накопленные очки, без Олимпиады и эстафет</span></div>{interactive&&<div className={styles.controls}><div><label htmlFor={prefix+'-left'}>Первый спортсмен</label><select id={prefix+'-left'} value={left} onChange={e=>setLeft(e.target.value)}>{data.athletes.map(a=><option value={a.key} key={a.key}>{a.name}</option>)}</select></div><div><label htmlFor={prefix+'-right'}>Второй спортсмен</label><select id={prefix+'-right'} value={right} onChange={e=>setRight(e.target.value)}>{data.athletes.map(a=><option value={a.key} key={a.key}>{a.name}</option>)}</select></div></div>}
 <div className={styles.legend}><span className={styles.first}>{la.name}: <b>{ls.points}</b></span><span className={styles.second}>{ra.name}: <b>{rs.points}</b></span></div><svg className={styles.chart} viewBox="0 0 680 314" role="img" aria-labelledby={prefix+'-chart-title '+prefix+'-chart-desc'}><title id={prefix+'-chart-title'}>Накопление очков: {la.name} и {ra.name}</title><desc id={prefix+'-chart-desc'}>Порядок 21 зачётной гонки, а не равномерная шкала дней. Финальный счёт {ls.points} против {rs.points}. Таблица всех гонок доступна ниже. Горизонтальный отрезок не означает нулевое место.</desc>{[0,1,2,3,4].map(k=>{const value=maximum*k/4;return <g key={k}><line x1="48" x2="646" y1={y(value)} y2={y(value)} className={styles.gridLine}/><text x="39" y={y(value)+4} textAnchor="end" className={styles.axis}>{value}</text></g>})}<polyline points={poly(pointsLeft)} className={styles.lineLeft}/><polyline points={poly(pointsRight)} className={styles.lineRight}/>{rows.map(r=><g key={r.raceId}><circle cx={x(r.index)} cy={y(r.leftTotal)} r="3" className={styles.dotLeft}><title>{short(r.date)} {la.name}: {r.leftTotal} очков; {r.left?'место '+r.left[0]:'нет записи в протоколе'}</title></circle><rect x={x(r.index)-3} y={y(r.rightTotal)-3} width="6" height="6" className={styles.dotRight}><title>{short(r.date)} {ra.name}: {r.rightTotal} очков; {r.right?'место '+r.right[0]:'нет записи в протоколе'}</title></rect></g>)}{[1,8,14,21].map(i=><text key={i} x={x(i)} y="296" textAnchor="middle" className={styles.axis}>{short(rows[i-1].date)}</text>)}</svg>
 <p className={styles.note}>Шаг по горизонтали — одна зачётная гонка, не одинаковое число дней. Накопленные очки не обнуляются при отсутствии спортсмена. Промежуточная разница рассчитана по нынешней финальной версии результатов, не по архиву таблиц каждого дня.</p>
 <div className={styles.tableWrap} role="region" aria-label="Сводка сравнения" tabIndex={0}><table><caption>Классифицированные финиши и очки выбранных спортсменов</caption><thead><tr><th>Показатель</th><th>{la.name}</th><th>{ra.name}</th></tr></thead><tbody>{[['Финиши',ls.finishes,rs.finishes],['Победы',ls.wins,rs.wins],['Подиумы',ls.podiums,rs.podiums],['Топ-5',ls.top5,rs.top5],['Очки на подиумах',ls.podiumPoints,rs.podiumPoints],['Остальные очки',ls.otherPoints,rs.otherPoints]].map(([label,l,r])=><tr key={label}><th scope="row">{label}</th><td>{l}</td><td>{r}</td></tr>)}</tbody></table></div>
 <div className={styles.tableWrap} role="region" aria-label="Очки по частям сезона" tabIndex={0}><table><caption>Три календарных блока, не диагноз тренировочной формы</caption><thead><tr><th>Период</th><th>{la.name}</th><th>{ra.name}</th><th>Разница за блок</th></tr></thead><tbody>{['december','january','march'].map(phase=>{const l=athleteStats(data,left,phase),r=athleteStats(data,right,phase);return <tr key={phase}><th scope="row">{phaseLabel[phase]}</th><td>{l.points}</td><td>{r.points}</td><td>{signed(l.points-r.points)}</td></tr>})}</tbody></table></div>
 <p className={styles.note} role="status">Итоговая разница: {signed(final.gap)} очков для {la.name} относительно {ra.name}.</p>
 <details className={styles.details}><summary>Все 21 гонка: места, очки и первоисточники</summary><p className={styles.note}>В ячейке: место / очки / промахи по рубежам. «Нет записи» не заменяется DNS, DNF или нулевым местом.</p><div className={styles.tableWrap} role="region" aria-label="Полная таблица гонок" tabIndex={0}><table data-ledger-table><caption>Весь зачётный календарь; «Δ» — накопленная разница первого и второго спортсмена</caption><thead><tr><th>Дата и гонка</th><th>{la.name}</th><th>{ra.name}</th><th>Δ</th></tr></thead><tbody>{rows.map(r=><tr key={r.raceId}><th scope="row"><a href={sourceUrl(r.raceId)} target="_blank" rel="noopener noreferrer">{short(r.date)} · {venueLabel[r.venue]||r.venue} ↗</a><small>{disciplineLabel[r.discipline]}</small></th><td>{r.left?<>{r.left[0]} / <b>{r.left[1]}</b><small>{r.left[2]}</small></>:<span>Нет записи</span>}</td><td>{r.right?<>{r.right[0]} / <b>{r.right[1]}</b><small>{r.right[2]}</small></>:<span>Нет записи</span>}</td><td>{signed(r.gap)}</td></tr>)}</tbody></table></div></details>
 <div className={styles.links}><a href="/api/editorial/season-2526.csv">Скачать CSV: 6 спортсменов × 21 гонка</a>{!interactive&&<Link href="/media/season-2025-26">Сравнить других спортсменов →</Link>}</div><p className={styles.note}>Источник: итоговые протоколы IBU Datacenter. Суммы шести спортсменов сверены с общим зачётом; это не полный анализ лыжной скорости или причин изменения результатов.</p></section>;
}
