'use client';
import {useId,useState} from 'react';import data from '../../content/editorial/xc-season-2526.json';import {xcTable,xcLeader,xcClasses,xcTotals} from '../../lib/xc-standings.mjs';import styles from './Xc.module.css';
export function XcDataExplorer(){const id=useId(),[gender,setGender]=useState('men'),[classification,setClassification]=useState('overall'),[selected,setSelected]=useState('3422819');const table=xcTable(data,gender,classification),athlete=xcLeader(data,gender,selected),totals=xcTotals(data,athlete),source=xcTable(data,gender,'overall');
 function switchGender(value:string){setGender(value);setSelected(data.leaders.find(a=>a.gender===value)!.fisCode)}
 return <section className={styles.explorer} data-xc-explorer><div className={styles.controls}><div><label htmlFor={id+'-gender'}>Категория FIS</label><select id={id+'-gender'} value={gender} onChange={e=>switchGender(e.target.value)}><option value="men">Мужчины</option><option value="women">Женщины</option></select></div><div><label htmlFor={id+'-classification'}>Зачёт FIS</label><select id={id+'-classification'} value={classification} onChange={e=>setClassification(e.target.value)}>{Object.entries(xcClasses).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></div></div>
 <h2>{xcClasses[classification]} · {gender==='men'?'мужчины':'женщины'}</h2><p className={styles.note}>Первые шесть мест официального финала. Выборка каждого зачёта отдельная; отсутствие фамилии в шестёрке не означает ноль очков.</p><ol className={styles.bars} data-xc-ranking>{table.rows.map(r=><li key={r.fisCode}><div><span>{r.rank}. {r.name}<small>{r.nation} · FIS {r.fisCode}</small></span><b>{r.points}</b></div><div className={styles.track} aria-hidden="true"><span style={{width:`${100*r.points/table.rows[0].points}%`}}/></div></li>)}</ol><a href={table.sourceUrl} target="_blank" rel="noopener noreferrer">Официальный PDF этого зачёта ↗</a>
 <section className={styles.detail}><div className={styles.controls}><div><label htmlFor={id+'-athlete'}>Разобрать общий счёт</label><select id={id+'-athlete'} value={selected} onChange={e=>setSelected(e.target.value)}>{data.leaders.filter(a=>a.gender===gender).map(a=><option key={a.fisCode} value={a.fisCode}>{a.name}</option>)}</select></div></div><h2>{athlete.name}: {totals.overall} очков</h2><div className={styles.parts} data-xc-components>{[['Дистанции',totals.distance],['Спринты',totals.sprint],['Итог Tour de Ski',totals.tourTotal]].map(([label,n])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div><p className={styles.formula} role="status">{`${totals.distance} + ${totals.sprint} + ${totals.tourTotal} = ${totals.overall}`}</p><p className={styles.note}>Бонусные очки уже включены в гоночные начисления. В таблице 28 колонок: 27 отдельных гонок и один итог многодневки. Это не 28 самостоятельных финишей.</p>
 <details className={styles.details}><summary>Показать все 28 колонок начислений</summary><div className={styles.tableWrap} role="region" aria-label="Начисления FIS по колонкам" tabIndex={0}><table data-xc-allocations><caption>Очки и места из итоговой ведомости, не отдельный архив старт-листов</caption><thead><tr><th>Дата и событие</th><th>Место в источнике</th><th>Очки всего</th><th>Включённый бонус</th></tr></thead><tbody>{data.slots.map((s,i)=>{const c=athlete.allocations[i];return <tr key={s.column} className={s.kind==='tour_total'?styles.tour:undefined} data-score-kind={s.kind}><th scope="row"><time dateTime={s.date}>{s.date.slice(8,10)}.{s.date.slice(5,7)}</time> · {s.venue}<small>{s.label}</small>{s.kind==='tour_total'&&<b>Не отдельная гонка</b>}</th>{c?<><td>{c[1]}</td><td>{c[0]}</td><td>{c[2]}</td></>:<td colSpan={3}>Пустая ячейка зачёта</td>}</tr>})}</tbody></table></div><p className={styles.note}>Пустая ячейка не переименовывается в DNS, DNF или отсутствие участия. Для статуса нужен отдельный протокол. Нулевое начисление за итог тура также не объясняет причину.</p></details>
 <a href={source.sourceUrl} target="_blank" rel="noopener noreferrer">Проверить исходную строку общего зачёта ↗</a><p className={styles.note}>Получено {source.fetchedAt.slice(0,10)}. SHA-256 документа: <code>{source.sha256.slice(0,20)}…</code>. Все 28 ячеек и три составляющие сверены с отдельными таблицами FIS.</p></section><div className={styles.download}><a href="/api/editorial/xc-season-2526.csv">Скачать CSV: 12 участников × 28 колонок</a><p className={styles.note}>336 ячеек начислений, не 336 стартов. Файл содержит вид зачёта, место, включённый бонус, URL, хеш и дату получения. Исторические очки не являются прогнозом сезона 2026/27.</p></div></section>;
}
