'use client';
import {useState} from 'react';import Link from 'next/link';import {useReadingList} from './useReadingList';import {readingRows,type ReadingArticle} from '../../lib/reading-list.mjs';import {countLabel} from '../../lib/count-label.mjs';import styles from './Reading.module.css';
const labels:Record<string,string>={unread:'Не прочитано',read:'Прочитано',updated:'Новая версия',unavailable:'Сейчас недоступно'};
export function ReadingLibrary({articles,unavailable,partial}:{articles:ReadingArticle[];unavailable:boolean;partial:boolean}){
 const list=useReadingList(),[filter,setFilter]=useState('all'),[sport,setSport]=useState('all'),[confirm,setConfirm]=useState(false),[notice,setNotice]=useState('');
 const rows=readingRows(list.data,unavailable?[]:articles),visible=rows.filter(r=>(filter==='all'||filter==='unread'&&['unread','updated'].includes(r.state)||filter==='read'&&r.state==='read')&&(sport==='all'||r.article?.sport===sport));
 const remove=(slug:string)=>{const ok=list.mutate({kind:'remove',slug});setNotice(ok?'Материал убран из списка.':'Не удалось убрать материал.')};
 return <section aria-label="Моя библиотека" className={styles.library}>
  <noscript><p className={styles.notice}>Список хранится в этом браузере. Включите JavaScript, чтобы его открыть. <Link href="/media">Все статьи доступны без JavaScript →</Link></p></noscript>
  {list.status==='loading'?<p className={styles.notice}>Читаем список из этого браузера…</p>:list.status!=='ready'?<div className={styles.notice} role="status"><p>{list.error}</p><button type="button" onClick={list.reload}>Проверить доступ ещё раз</button></div>:<>
   {(unavailable||partial)&&<p className={styles.notice} role="status">{unavailable?'Не удалось получить проверенные статьи с сервера. Закладки сохранены, но тексты сейчас не подставляются.':'Часть статей временно скрыта до проверки. Закладки не удалены.'}</p>}
   <div className={styles.filters}><div><label htmlFor="reading-status">Статус чтения</label><select id="reading-status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все сохранённые</option><option value="unread">Не прочитано / новая версия</option><option value="read">Прочитано</option></select></div><div><label htmlFor="reading-sport">Вид спорта в списке</label><select id="reading-sport" value={sport} onChange={e=>setSport(e.target.value)}><option value="all">Все виды</option><option value="biathlon">Биатлон</option><option value="cross_country">Лыжные гонки</option></select></div></div>
   <p className={styles.summary} data-reading-summary>{countLabel(list.data.items.length,'сохранённый материал','сохранённых материала','сохранённых материалов')} · показано {visible.length}</p>
   {!rows.length?<div className={styles.empty}><h2>Здесь будет ваше чтение на потом.</h2><p>Нажмите «Читать позже» на карточке или в статье. Список появится здесь, без аккаунта.</p><Link href="/media">Выбрать материалы →</Link></div>:!visible.length?<div className={styles.empty}><h2>Нет материалов по выбранным условиям</h2><button type="button" onClick={()=>{setFilter('all');setSport('all')}}>Показать весь список</button></div>:<div className={styles.list}>{visible.map(({entry,article,state})=><article key={entry.slug} className={styles.item} data-reading-entry={article?.slug||'unavailable'}><div className={styles.itemMeta}><span>{article?(article.sport==='cross_country'?'ЛЫЖНЫЕ ГОНКИ':'БИАТЛОН'):'СОХРАНЁННАЯ ССЫЛКА'}</span><b className={state==='updated'?styles.changed:''}>{labels[state]}</b></div>{article?<><h2><Link href={'/media/'+article.slug}>{article.title}</Link></h2><p>{article.dek}</p><small>{article.readMinutes} мин · сохранено {new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',timeZone:'Europe/Moscow'}).format(entry.savedAt)}</small><div className={styles.actions}><Link href={'/media/'+article.slug}>{state==='read'?'Перечитать →':'Открыть статью →'}</Link><button type="button" aria-label={`Отметить прочитанным: ${article.title}`} aria-pressed={state==='read'} onClick={()=>{const ok=list.mutate({kind:'read',slug:entry.slug,revision:article.bodySha256,read:state!=='read'});setNotice(ok?(state==='read'?'Пометка снята.':'Текущая версия отмечена прочитанной.'):'Пометка не сохранена.')}}>{state==='read'?'Прочитано':'Отметить прочитанным'}</button><button type="button" onClick={()=>remove(entry.slug)} aria-label={`Убрать из сохранённых: ${article.title}`}>Убрать</button></div></>:<><h2>Сохранённый материал сейчас недоступен</h2><p>Он может быть временно скрыт или отсутствовать в текущем каталоге. Не показываем название и ссылку из непроверенных локальных данных.</p><button type="button" onClick={()=>remove(entry.slug)}>Убрать недоступную закладку</button></>}</article>)}</div>}
  </>}
  <p role="status" aria-atomic="true" className={styles.status}>{notice}{list.status==='ready'&&list.error?' '+list.error:''}</p>
  {(list.data.items.length>0||list.status==='corrupt')&&<div className={styles.reset}>{!confirm?<button type="button" onClick={()=>setConfirm(true)}>{list.status==='corrupt'?'Сбросить повреждённый список…':'Очистить сохранённые материалы…'}</button>:<><p>Будут удалены только закладки статей и их пометки. Избранные этапы и гонки «Моего сезона» останутся.</p><div className={styles.actions}><button type="button" onClick={()=>{if(list.reset()){setNotice('Список статей очищен. Избранные гонки не изменены.');setConfirm(false)}}}>Да, очистить список статей</button><button type="button" onClick={()=>setConfirm(false)}>Не очищать</button></div></>}</div>}
  <p className={styles.privacy}>В этом браузере хранятся только идентификатор статьи, номер её версии, дата сохранения и ваша ручная пометка «прочитано». Полные тексты не сохраняются для офлайн-чтения. Список не отправляется проектом в базу, не синхронизируется между устройствами и может исчезнуть при очистке данных браузера. На общем устройстве он доступен другим пользователям этого браузера. Чтение и прокрутка сами по себе ничего не отмечают.</p>
 </section>;
}
