import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteNav} from '../../../components/SiteNav';
import {getRace} from '../../../lib/data';
import {supabase} from '../../../lib/supabase';
import {formatDate,genderLabel,jsonForHtml,raceStart,raceStatus,safeHttpsUrl,sportLabel} from '../../../lib/domain.mjs';
import {pageMetadata,siteOrigin} from '../../../lib/seo';
export const dynamic='force-dynamic';
type Props={params:Promise<{id:string}>};
export async function generateMetadata({params}:Props){const {id}=await params;const r=await getRace(id);return r?pageMetadata(`${r.discipline} — ${r.location || r.series}, ${r.event_date || 'дата уточняется'}`,`${sportLabel(r.sport)}. ${genderLabel(r.gender)}. ${raceStatus(r.status)}. Программа, первоисточник и проверенные трансляции.`,`/race-center/${r.id}`):{title:'Гонка не найдена',robots:{index:false,follow:false}};}
export default async function RacePage({params}:Props){
 const r=await getRace((await params).id); if(!r)notFound();
 const [{data:streams,error:streamError},{data:results,error:resultError}]=await Promise.all([
  supabase.from('streams').select('id,label,url,platform,region,verified_at,rights_status').eq('event_id',r.id).in('rights_status',['official','authorized']).not('verified_at','is',null),
  supabase.from('athlete_results').select('id,rank,finish_time_seconds,source_url,athletes(full_name)').eq('event_id',r.id).not('source_url','is',null).order('rank').limit(100)
 ]);
 const source=safeHttpsUrl(r.source_url), start=raceStart(r.event_date,r.start_time_msk);
 const schema=siteOrigin&&start&&r.location&&r.status!=='tentative'&&r.status!=='provisional'?{'@context':'https://schema.org','@type':'SportsEvent',name:`${sportLabel(r.sport)}: ${r.discipline} — ${genderLabel(r.gender)}`,startDate:start,url:`${siteOrigin}/race-center/${r.id}`,sport:sportLabel(r.sport),location:{'@type':'Place',name:r.location,...(r.country?{address:{'@type':'PostalAddress',addressCountry:r.country}}:{})},...(r.status==='cancelled'?{eventStatus:'https://schema.org/EventCancelled'}:{})}:null;
 return <main id="main-content"><SiteNav/>{schema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonForHtml(schema)}}/>}<header><div className="eyebrow">{sportLabel(r.sport)} · {genderLabel(r.gender)}</div><h1 className="detailTitle">{r.discipline}</h1><p className="lead">{r.series} · {r.location || 'Место уточняется'}{r.distance?' · '+r.distance:''}</p><div className="detailFacts"><span>{formatDate(r.event_date)}</span><span>{r.start_time_msk?`${r.start_time_msk.slice(0,5)} МСК`:'Время не опубликовано'}</span><span className={'status '+r.status}>{raceStatus(r.status)}</span></div></header><div className="grid"><section><article className="panel"><h2>Трансляция</h2>{streamError?<p>Не удалось проверить список трансляций.</p>:streams?.length?streams.map(s=>safeHttpsUrl(s.url)&&<p key={s.id}><a href={safeHttpsUrl(s.url)!} rel="noopener noreferrer" target="_blank">{s.label} ↗</a> · {s.region || 'Регион уточняется'}</p>):<p>В базе пока нет проверенной ссылки правообладателя для этой гонки. Это не означает, что трансляции не будет.</p>}</article><article className="panel"><h2>Результаты</h2>{resultError?<p>Результаты временно недоступны.</p>:results?.length?<div className="tableScroll"><table><caption>Опубликованные записи; первоисточник содержит полный протокол и его статус.</caption><thead><tr><th>Место</th><th>Спортсмен</th><th>Протокол</th></tr></thead><tbody>{results.map(row=><tr key={row.id}><td>{row.rank ?? '—'}</td><td>{(Array.isArray(row.athletes)?row.athletes[0]:row.athletes)?.full_name || 'Имя уточняется'}</td><td>{safeHttpsUrl(row.source_url)&&<a href={safeHttpsUrl(row.source_url)!} target="_blank" rel="noopener noreferrer">Источник ↗</a>}</td></tr>)}</tbody></table></div>:<p>В базе пока нет опубликованного протокола этой гонки. Старт-лист и итоговые результаты — разные документы.</p>}</article></section><aside><article className="panel"><small>ПРОИСХОЖДЕНИЕ ДАННЫХ</small><h2>Проверяемо</h2>{source&&<a className="watchButton" href={source} target="_blank" rel="noopener noreferrer">Открыть первоисточник ↗</a>}<p>Последняя зафиксированная проверка: {r.verified_at?new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',dateStyle:'medium',timeStyle:'short'}).format(new Date(r.verified_at))+' МСК':'не указана'}.</p><p>Оценка источника {r.source_confidence ?? '—'}/5 не гарантирует неизменность расписания.</p><Link href="/methodology">Правила проверки и исправлений →</Link></article></aside></div></main>;
}
